### ISSUE TITLE
"Please confirm that you want to add the item(s) listed below to your cart.

### ISSUE THREAD

**Issue by myn** [Hari-Nagarajan/fairgame#149]
Got latest from master branch and getting a "Please confirm that you want to add the item(s) listed below to your cart.

These items are currently unavailable:
PlayStation 5 Console
PlayStation 5 Digital Edition
PULSE 3D Wireless Headset

**Comment by Hari-Nagarajan** [comment]
Yes that's the correct output. It tries to add to cart until the items go into cart and then it goes through the checkout flow.

**Comment by myn** [comment]
> Yes that's the correct output. It tries to add to cart until the items go into cart and then it goes through the checkout flow.

If one of the items in the list comes back into stock it proceeds to buy just that one and will automatically resume checking for the others in the list afterwards?

**Comment by Hari-Nagarajan** [comment]
No it ends after a successful purchase

**Comment by myn** [comment]
So If have 3 distinct amazon products (ps5, controller and say a headset) it will stop after it buys the controller?

Thoughts on making the list inclusive to buying all items in list, not just one of them?

**Comment by freejack** [comment]
> So If have 3 distinct amazon products (ps5, controller and say a headset) it will stop after it buys the controller?
> 
> Thoughts on making the list inclusive to buying all items in list, not just one of them?

If they're all in stock it'll buy all of them.

**Comment by myn** [comment]
> > So If have 3 distinct amazon products (ps5, controller and say a headset) it will stop after it buys the controller?
> > Thoughts on making the list inclusive to buying all items in list, not just one of them?
> 
> If they're all in stock it'll buy all of them.

What if 1 is but the other 2 aren't?  Will it buy that 1 and then resume attempting to buy the other 2?

**Comment by DakkJaniels** [comment]
old code
