### ISSUE TITLE
Amazon auto checkout fails due to address/payment confirmation.

### ISSUE THREAD

**Issue by Illandren** [Hari-Nagarajan/fairgame#169]

**Comment by Hari-Nagarajan** [comment]
Have you set up defaults for these?

**Comment by Illandren** [comment]
Even when set to defaults, it seems to want to confirm address and payment method. I was able to add some functionality in finalize_order_button and checkout in amazon.py to work with it, but my python is mediocre at best.

finalize_order_button xpath additions:
` 
'//*[@id="shipToThisAddressButton"]/span/input',
`
` 
'//*[starts-with(@data-pmts-component-id, "pp") and contains(@class, "button")]',
`

new checkout:
` 

    def checkout(self, test):
        log.info("Clicking continue.")
        self.driver.find_element_by_xpath('//input[@value="add"]').click()

        log.info("Waiting for Cart Page")
        self.check_if_captcha(self.wait_for_pages, SHOPING_CART_TITLES)

        log.info("clicking checkout.")
        self.driver.find_element_by_xpath('//*[@id="sc-buy-box-ptc-button"]/span/input').click()

        log.info("Waiting for Place Your Order Page")
        self.wait_for_pyo_page()

        log.info("Confirming Address")
        self.finalize_order_button(test)

        log.info("Waiting for Place Your Order Page")
        self.wait_for_pyo_page()

        log.info("Confirming Payment Method")
        self.finalize_order_button(test)

        log.info("Waiting for Place Your Order Page")
        self.wait_for_pyo_page()

        log.info("Checking out")
        time.sleep(1)
        self.finalize_order_button(test)

        log.info("Waiting for Order completed page.")
        self.wait_for_order_completed(test)

        log.info("Order Placed.")
`

**Comment by DakkJaniels** [comment]
need to turn on one click ordering
