### ISSUE TITLE
Improve element lookup

### ISSUE THREAD

**Issue by WillsB3** [Hari-Nagarajan/fairgame#179]
While looking through the EVGA script I noticed XPATHs [like this](https://github.com/Hari-Nagarajan/nvidia-bot/blob/master/stores/evga.py#L202): `/html/body/form/div[3]/div[3]/div/div[1]/div[5]/div[3]/div/div[1]/div/div[@id='checkoutButtons']/input[2]`.

This feels very brittle - one slight template change and this will break. The buttons appear to have IDs on so we should just be able to target them by ID which would make this more robust.

**Comment by Hari-Nagarajan** [comment]
The EVGA site reuses IDs. So search by IDs fails.
