### ISSUE TITLE
Amazon bot times out on the Proceed to Checkout Page

### ISSUE THREAD

**Issue by drod3763** [Hari-Nagarajan/fairgame#228]
Looks like the Amazon Bot successfully add something to the cart, but on the cart page just before checkout it times out. I just pulled latest and will test some more but here are some screenshots.

![Cart](https://user-images.githubusercontent.com/7785716/95095549-2e661f00-06f9-11eb-8875-70b141422721.png)
![Log](https://user-images.githubusercontent.com/7785716/95095573-3625c380-06f9-11eb-89a8-8c32dd62be94.png)

**Comment by worst-mod-confirmed** [comment]
Update to the latest. This was likely an issue with your browser being minimized.
