### ISSUE TITLE
Amazon Double-Password Entry and Window Closure

### ISSUE THREAD

**Issue by BR4SH** [Hari-Nagarajan/fairgame#247]
Upon arriving at the password entry page, the password is entered twice with a sign-in failure, then re-initiated with a mandatory captcha, after which completing manually, causes the window to close (or crash) upon the text verification page loading.

> (nvidia-bot-4MUBJ5qs) C:\Users\**\Desktop\repos\nvidia-bot>python app.py amazon
> 2020-10-08 23:19:25 DESKTOP-IDT3076 nvidia-bot[2948] INFO Initializing Apprise handler
> 2020-10-08 23:19:25 DESKTOP-IDT3076 nvidia-bot[2948] INFO Initializing other notification handlers
> 2020-10-08 23:19:25 DESKTOP-IDT3076 nvidia-bot[2948] INFO Enabled Handlers: ['Audio']
> 
> DevTools listening on ws://127.0.0.1:49613/devtools/browser/d358dc4b-f570-46b6-9ec9-3d637360f264
> [21744:1308:1008/231926.539:ERROR:CONSOLE(1)] "Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'strict-dynamic' 'sha256-1+GSDjMMklBjZY0QiWq+tGupCvajw4Xbn46ect2mZgM=' 'sha256-2mX1M62Fd0u8q0dQY2mRsK5S1NS9jJuQAvyE8tD0dkQ=' 'sha256-EtIKSV82ixJHE3AzqhoiVbUGKG+Kd8XS0fFToow29o0=' 'sha256-QSyFltV9X3gkyBrg+SMfKvZNXmqPQc6K4B6OYhTuXmw=' 'sha256-ANdtIo91Yk/zh1YKZ+IXKP1pb00awOjEFMAUld02F6A=' 'sha256-CbH+xPsBKQxVw5d9blISLDeuMSe1M+dJ4xfArFynIfw=' 'sha256-lA+EURA/fC0TZq1ATYZvxIQHBc9iTAaBcI+dFMmTn9I=' 'sha256-aqD9EtZjsMp7vVxEx5UIIO14I4GzQ+1TRs8P2PkoWRg='". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.
> ", source: chrome-search://local-ntp/local-ntp.html (1)
> {'BASE_URL': 'https://www.amazon.com/', 'CART_URL': 'https://www.amazon.com/gp/aws/cart/add.html'}
> 2020-10-08 23:19:29 DESKTOP-IDT3076 nvidia-bot[2948] INFO Waiting for home page.
> 2020-10-08 23:19:29 DESKTOP-IDT3076 nvidia-bot[2948] INFO Lets log in.
> 2020-10-08 23:19:31 DESKTOP-IDT3076 nvidia-bot[2948] INFO Wait for Sign In page
> 2020-10-08 23:19:31 DESKTOP-IDT3076 nvidia-bot[2948] INFO Email
> 2020-10-08 23:19:31 DESKTOP-IDT3076 nvidia-bot[2948] INFO Remember me checkbox
> 2020-10-08 23:19:32 DESKTOP-IDT3076 nvidia-bot[2948] INFO Password
> 2020-10-08 23:19:33 DESKTOP-IDT3076 nvidia-bot[2948] INFO Logged in as email@email.com
> 2020-10-08 23:19:33 DESKTOP-IDT3076 nvidia-bot[2948] INFO Waiting 15 seconds.
> 2020-10-08 23:19:48 DESKTOP-IDT3076 nvidia-bot[2948] INFO Checking stock for items.
> Traceback (most recent call last):
>   File "app.py", line 5, in <module>
>     cli.main()
>   File "C:\Users\**\.virtualenvs\nvidia-bot-4MUBJ5qs\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Users\**\.virtualenvs\nvidia-bot-4MUBJ5qs\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\**\.virtualenvs\nvidia-bot-4MUBJ5qs\lib\site-packages\click\core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Users\**\.virtualenvs\nvidia-bot-4MUBJ5qs\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Users\**\.virtualenvs\nvidia-bot-4MUBJ5qs\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Users\**\Desktop\repos\nvidia-bot\cli\cli.py", line 27, in decorator
>     func(*args, **kwargs)
>   File "C:\Users\**\Desktop\repos\nvidia-bot\cli\cli.py", line 81, in amazon
>     amzn_obj.run_item(test=test)
>   File "C:\Users\**\Desktop\repos\nvidia-bot\stores\amazon.py", line 156, in run_item
>     while not self.something_in_stock():
>   File "C:\Users\**\Desktop\repos\nvidia-bot\stores\amazon.py", line 172, in something_in_stock
>     self.driver.get(f.url)
>   File "C:\Users\**\.virtualenvs\nvidia-bot-4MUBJ5qs\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
>     self.execute(Command.GET, {'url': url})
>   File "C:\Users\**\.virtualenvs\nvidia-bot-4MUBJ5qs\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "C:\Users\**\.virtualenvs\nvidia-bot-4MUBJ5qs\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: chrome not reachable
>   (Session info: chrome=85.0.4183.121)

**Comment by fokeiro2020** [comment]
delete the .amazon-profile folder , that will fix it

**Comment by BR4SH** [comment]
> delete the .amazon-profile folder , that will fix it

Thank you for the advice! I'll give it a shot later this evening.

**Comment by BR4SH** [comment]
> delete the .amazon-profile folder , that will fix it

Are you talking about the config file or something else? I don't see an amazon-profile folder.

**Comment by BR4SH** [comment]
The issue persists once you change the Amazon website in the config file to the .com from co.uk.

Any ideas?

**Comment by BR4SH** [comment]
Update: The Amazon account username and password entries now enter successfully, but a manual capthca must still be completed, after which, the account is still never signed into.

**Comment by worst-mod-confirmed** [comment]
Closing this as its been almost 2 months. Update to the latest code base and reopen this ticket if the issue persists.
