### ISSUE TITLE
Change the Amazon log in process to prevent account locked out

### ISSUE THREAD

**Issue by Dr8g0n** [Hari-Nagarajan/fairgame#251]
Can we change the login flow for Amazon? 

Search for Nvidia products anonymously and only log in after it gets successfully added to the shopping cart. Doing this way to prevent the recent account-specific locked out.

Thanks!

**Comment by luigi311** [comment]
Only thing i can think of is that will add time to the purchase process. Depending on how fast it sells out that time might matter.

**Comment by worst-mod-confirmed** [comment]
No, the potential for missing the checkout window is too big with this.
