### ISSUE TITLE
Canadian Best Buy Support

### ISSUE THREAD

**Issue by StructureChaos** [Hari-Nagarajan/fairgame#259]
Hello,

I'm not much of a programmer but from my limited understanding of coding and a bit of basic testing, it seems like all of the commands related to bestbuy all return back to the American version of the website and directs to American versions of the log in page. If I am correctly understanding this (and there is a good chance I am not) does all of the code relating to https://www.bestbuy.com/ have to be replaced with a https://www.bestbuy.ca equivalent. If you try and submit a request for a "https://www.bestbuy.ca/checkout/r/payment" as opposed to "https://www.bestbuy.com/checkout/r/payment". Could I have clarification on if it is possible for the bots to function on the Canadian version of the website and if not could that functionality be added.

![USA vs Canada difference two](https://user-images.githubusercontent.com/73426046/97107414-c1adc700-169d-11eb-9ac7-765bcdf26ca6.png)
![USA vs Canada difference](https://user-images.githubusercontent.com/73426046/97107415-c1adc700-169d-11eb-9083-502e92dc2b8b.png)

**Comment by DakkJaniels** [comment]
I think the api.bestbuy.com stuff is US only. It looks like that API is being used in two places, the first being on initialization, to get the product URL based on the SKU, and the second is used to add the item to your cart. I'm not sure why the first happens, it doesn't seem that is used anywhere else - maybe that can be commented out. The second though is not going to work, so you'd have to figure out a work around for that, or just remove that functionality.

Regardless, all the payment/checkout stuff is not active, so updating that won't matter. If you at least want stock alerts, you'd have to figure out an equivalent link in the .ca version of the site to replace the url at [https://github.com/Hari-Nagarajan/nvidia-bot/blob/053a02d68398dcd3892197bd37c7d3fd33f09cb1/stores/bestbuy.py#L160](url).
