### ISSUE TITLE
Enhancement: Walmart.com

### ISSUE THREAD

**Issue by sbaraka** [Hari-Nagarajan/fairgame#284]
I think this is a pretty big and obvious one. Walmart has an excess amount of stock. Think it would be good

**Comment by DakkJaniels** [comment]
Go for it!

**Comment by sbaraka** [comment]
Where did the discord invite go?

**Comment by DakkJaniels** [comment]
It's in the readme

**Comment by R1fast** [comment]
+1 on this enhancement being its PS5 launch day and all. 👍

**Comment by sbaraka** [comment]
Invalid invite it sayd

**Comment by agmeadows** [comment]
I am working on a Walmart script. It is nearly complete. The only thing stopping me is the occasional ReCaptcha requests I cannot reliably defeat.

**Comment by agmeadows** [comment]
I submitted my Walmart script. I was able to secure an Xbox so there is no reason for me to continue developing it. It is based on amazon.py and I have tested it all the way to order complete. I included 2captcha integration to defeat ReCaptcha but I could not get it to work. It is rough around the edges. Hopefully it is useful to someone.
