### ISSUE TITLE
Add batch files to buy a PS5

### ISSUE THREAD

**Issue by Das-Morgenstern** [Hari-Nagarajan/fairgame#287]
(NOT AN ISSUE WITH CODE)
As a gamer, I was angry at the events that took place in the RTX30 series demand and how scalpers took over basically the entire market but now it's happening to other platforms as well. The newer PS5s and XBOX Series X were released a couple days ago and the same thing is happening there. I think the community would appreciate some help there seeing that it would be as easy as adding a batch file and rewriting some of the read.md file.

**Comment by DakkJaniels** [comment]
I guess Best Buy has a batch file, but the bots don't really work well with it anyway, and Amazon doesn't have anything like that. The amazon bot requires you to fill in the ASIN numbers for the products you want. I don't think we want to get into maintaining ASIN lists for different products. Any person downloading the bot can update the amazon config file with the ASINs they want, including XBOX Series X and the PS5.

If you have suggestions for README updates, feel free to make a pull request with them.

**Comment by Das-Morgenstern** [comment]
Yeah, I could see that. I guess I'll make a pull request when I get home. I've had luck with adding ASIN numbers that weren't on the list before, so I guess people who really want it can do it themselves. It was more about just advertising it to be used for both GPUs and consoles.

**Comment by Das-Morgenstern** [comment]
@DakkJaniels So I've made batch files and ASIN numbers for the consoles, my only question is, how do I submit these files for publishing without it taking my Amazon information with it?

**Comment by DakkJaniels** [comment]
amazon_config.json will not upload to GitHub. Did you put that stuff in the .bat files?

**Comment by Das-Morgenstern** [comment]
> amazon_config.json will not upload to GitHub. Did you put that stuff in the .bat files?

No I did not. I saw in the GitHub desktop app that there wasn't a file change registered for the amazon_config file but I wanted to be sure.

**Comment by DakkJaniels** [comment]
Yup it will only include the changed files

**Comment by Das-Morgenstern** [comment]
Alright I think I've uploaded it. Correct me if I'm wrong.

**Comment by DakkJaniels** [comment]
Sorry missed this - did you make a pull request? Or did you upload change to your own fork?
