### ISSUE TITLE
browser close or script exit will not release resources held by chrome/chromedriver

### ISSUE THREAD

**Issue by heavyarms2112** [Hari-Nagarajan/fairgame#305]
I can only run the script successfully one time.  The chrome browser session doesn't exit when hit Ctrl+C or closing the browser sessions with 'X' on Windows 10.

Next time I run the script i get prompted with below error.
`ERROR Message: unknown error: Chrome failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location C:\Program Files (x86)\Google\Chrome\Application\chrome.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
`
A workaround is to go to task manager and kill chrome.exe (specific PID)

**Comment by unapproachable** [comment]
Hopefully addressed by https://github.com/Hari-Nagarajan/fairgame/pull/410
