### ISSUE TITLE
When an item is in stock, amazon bot doesnt click the select address button for cross country purchases.

### ISSUE THREAD

**Issue by SirDystic** [Hari-Nagarajan/fairgame#323]
When an item is in stock, amazon bot doesnt click the select address button for cross country purchases.

So for for instance if ordering to a UK address from Amazon.de, the checkout process hangs on the select address page:

![amazon2](https://user-images.githubusercontent.com/74874762/99963739-2128f080-2d8a-11eb-85de-e5579b9dbfb4.jpg)
![amazon1](https://user-images.githubusercontent.com/74874762/99963744-22f2b400-2d8a-11eb-9764-db103dcd487a.jpg)
 
(address blanked out below for privacy)

**Comment by DakkJaniels** [comment]
Sorry, don't speak French or German, so not really sure what you are looking for the bot to do here? How is it supposed to know what address you want to use or what button it is supposed to click?

**Comment by AleG911** [comment]
I usually order from USA but I don't live there. This also happen to me, I fixed it selecting the corresponding address instead of the zip code on the top left corner of Amazon Home page
![image](https://user-images.githubusercontent.com/54762669/100325273-01621a00-2f8e-11eb-86c6-f69452380ee0.png)
