### ISSUE TITLE
Order completed - but it is not in my order history and doesn't exist.

### ISSUE THREAD

**Issue by Dethlore** [Hari-Nagarajan/fairgame#366]
**Describe the bug**
The bot ran as expected, found an item, clicked through everything and completed, but the actual order does not exist. It is not running in test mode.

**To Reproduce**
1. Run: python app.py amazon --no-image
2. Wait for stock to be available (maybe test this on a product that is in stock)

**Expected behavior**
I expect the order to exist.

**Screenshots**
![image](https://user-images.githubusercontent.com/8835489/100626760-72356900-32e3-11eb-964d-000d30a44a44.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: 47.0.4280.66

**Comment by Dethlore** [comment]
I'll leave this up to the mod's discretion... but I found the issue. Apparently, my wife purchased something at this time and the bot thought that it was the product it was looking at and falsely considered it as purchased. I don't know why it would have gone through the steps of clicking buttons and getting through the checkout page though....

**Comment by luigi311** [comment]
Ive usually seen this when amazon reports stock but the add to cart button does not add the item to the cart. When there is nothing on the cart the bot will go back and attempt to check stock again and add it to your cart. The problem is when something is already on the cart the bot will thing it is the item it was trying to add and checkout. My SO left something in the cart and i ended up purchasing it when this happened. Perhaps there should be a check to see if the item that it found is actually in the cart when going through the checkout process.

**Comment by DakkJaniels** [comment]
It might be possible, but how would we handle program flow of there was something already in cart? I assume is the product they wanted was also in the cart, they would want to proceed with purchase?

At this point, we can just add a warning about it at start up, unless someone wants to figure this out and make a PR.

**Comment by Dethlore** [comment]
Might be quickest and easiest to do a string find in the dom to find at least a partial match to the ASIN's product string? I don't think having to click into each product in cart and matching ASINs there would be necessary (since time is really of the essence), but would certainly be most precise.

**Comment by hwamil** [comment]
How about this:

1) Purge cart on start-up
2) Check presence of items in cart every n-th cycle and purge if bot did not detect any stock.

**Comment by DakkJaniels** [comment]
Sounds good, if you are going to implement @hwamil

**Comment by hwamil** [comment]
I would but I don't need or want this feature since I also shop regularly so getting my cart purged repeatedly would not be fun. Honestly, OP should just use another account or be on top of it.

**Comment by Dethlore** [comment]
no you're probably right... just stay on top of it myself or get a separate account would be the easiest... but if someone does want to go into improvements... then there's a suggestion.

**Comment by SalvadorSTM** [comment]
Thanks for bringing this up. Didnt even realize this was possible. Need to be careful.

**Comment by historypsi** [comment]
I've had this happen, just check your screen shots to validate what happened. My successful checkout screenshot showed "there was an issue with an item in your cart" so it was removed.

**Comment by Dethlore** [comment]
So there are some instances that it is something (I think) that should be logged as a bug if it's giving a successful checkout when the item is actually removed from cart.

**Comment by DakkJaniels** [comment]
this issue should be resolved (order placed when it did not occur) with latest master.
