### ISSUE TITLE
enhancment: automating bestbuy check after pc restart

### ISSUE THREAD

**Issue by jelizarovas** [Hari-Nagarajan/fairgame#374]
you can create automated script that you can start up whenever you want without having to fiddle with commands and locations.

create a new text file and name it `bestbuy 6429440.bat`

```
cd C:/Users/Arnas/Documents/GitHub/nvidia-bot
pipenv shell "/c python app.py bestbuy --sku 6429440"
```

off course change directory to where your repository is and the sku for whichever card you want.

**Comment by DakkJaniels** [comment]
Is this different from just using/editing the best buy batch files already in root?

**Comment by jelizarovas** [comment]
I was not aware of those. Good catch.
