### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by anumerical** [Hari-Nagarajan/fairgame#375]
Since the files are largely python we can convert the .bat files to .bash or .sh to run on linux systems. The subsequent steps are then available to run on linux. This can be done with each of the .bat files and upload it to the directory. Or you can maintain functionality of both by having a _Amazon.bat and a _Amazon.sh file so the user simply selects which one they want to run on their respective systems

**Comment by DakkJaniels** [comment]
Can't someone just rename .bat to .sh? or are there extra steps on linux?

**Comment by pinilpypinilpy** [comment]
even chmod 777 amazon.bat and ./amazon.bat would work, as the command is just starting Python.

**Comment by mateuszdrab** [comment]
Works fine for me on Linux, you don't need the bat files to start it.
