### ISSUE TITLE
No module named 'gi'

### ISSUE THREAD

**Issue by MaxandreOgeret** [Hari-Nagarajan/fairgame#381]
**Describe the bug**
Reports that "gi" is not available

**To Reproduce**
Follow install steps under ubuntu 18.04

**Expected behavior**
gi found and notifications can play

**Screenshots**
If applicable, add screenshots to help explain your problem. These are found in the bot directory.

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04

**Additional context**
Error message : 
```
2020-12-03 13:22:19  nvidia-bot[16626] INFO A notification was sent to the following handlers: Audio
2020-12-03 13:22:19  nvidia-bot[16626] ERROR No module named 'gi'
2020-12-03 13:22:19  nvidia-bot[16626] WARNING Error playing notification sound. Disabling local audio notifications.

```

**Comment by bmn001** [comment]
I get this too on Ubuntu 20.10.  Script seems to work otherwise.

**Comment by mahouko** [comment]
Was having same problem with Manjaro. Got it to work with...

`pip install vext

pip install vext.gi`

**Comment by DakkJaniels** [comment]
not an issue for running the bot, you just won't have audio unless you follow the above directions. Closing.
