### ISSUE TITLE
amazon support is dangerous, no?

### ISSUE THREAD

**Issue by bwanaaa** [Hari-Nagarajan/fairgame#413]
for example this page

https://www.amazon.com/ASUS-Graphics-DisplayPort-Axial-tech-2-9-Slot/dp/B08J6GMWCQ/ref=sr_1_1?dchild=1&keywords=B08J6GMWCQ&qid=1607636037&sr=8-1

lists the card for over 3k, obviously a scalper. Since we really do NOT want to buy any scalped items, aren't we simply doing a DDNS attack on amazon? asking for a product we really aren't interested in at that ridiculous price?

wouldn't newegg be a better vendor?

**Comment by DakkJaniels** [comment]
How do you propose checking for something on Amazon then? Feel free to start programming something for Newegg
