### ISSUE TITLE
Amazon fails to add to cart or check out. 

### ISSUE THREAD

**Issue by Aevets** [Hari-Nagarajan/fairgame#415]
**Describe the bug**
Bot is not adding to cart or checking out in stock items. 

**Expected behavior**
(W/item in stock) Bot clicks add to cart and checks out. 

**Screenshots**

![image](https://user-images.githubusercontent.com/75469503/101844033-bd802080-3b08-11eb-920e-7cec7da6b0aa.png)

![image](https://user-images.githubusercontent.com/75469503/101843703-07b4d200-3b08-11eb-819d-50debf7395d1.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser - chrome
 - Version -87.0.4280.88

**Additional context**
Bot searches for products, finds product but does not click add to cart. Watched bot fail to add to cart. Bot proceeds to refresh and try to add to cart again with no success. Tested bot on small kids toy as I've missed two 3080 drops via amazon now. checked reserve but it is set to 100 and product is $5.00. 

Anyone have any idea on if I need to update a line so bot clicks the add to cart button???  

Thank you for your time, 
Steve.

**Comment by DakkJaniels** [comment]
Update your code, you are using a version that's about a week old at this point. I have no problem hitting checkout with that exact same ASIN 
![image](https://user-images.githubusercontent.com/6080734/101845416-9cc1c600-3b1c-11eb-8692-79be3ad41767.png)

**Comment by Aevets** [comment]
YUP! thank you just figured it out. Sorry to waste your time!
