### ISSUE TITLE
Amazon Bot Does Not Work Properly

### ISSUE THREAD

**Issue by Ameno-Sagiri** [Hari-Nagarajan/fairgame#416]
**Describe the bug**
When the bot tries to login to amazon, it quickly enters the username twice in the username field, therefore erroring out and ending the task

**To Reproduce**
Use the bot as intended

**Expected behavior**
It should enter the username ONCE

**Desktop (please complete the following information):**
Windows 10
Chrome
fairgame 0.4.4

**Additional context**
```
2020-12-10 22:22:24 DESKTOP fairgame[1696] INFO Waiting for home page.
2020-12-10 22:22:25 DESKTOP fairgame[1696] INFO Lets log in.
2020-12-10 22:22:25 DESKTOP fairgame[1696] INFO Wait for Sign In page
2020-12-10 22:22:26 DESKTOP fairgame[1696] INFO Email
2020-12-10 22:22:26 DESKTOP fairgame[1696] ERROR Login failed, check your username in amazon_config.json

```

The first time I activated it, it worked perfectly fine. I shut it off and changed the parameters of which item to look for (shouldn't even be affecting the login process), and now it keeps rapidfire entering the username. If I manually log in for the bot, it doesn't matter because it had failed at attempting its own login, and kills itself. There needs to be a way to skip the bots login process if I can just save myself as logged in on the browser, or there needs to be a way to manually login for the bot, so it can just pickup from where I leave off on that browser window.

**Comment by Ameno-Sagiri** [comment]
Fixed by deleting .profile-amz

It appears the browser was autofilling

**Comment by DakkJaniels** [comment]
Correct, don't save your credentials to browser
