### ISSUE TITLE
Added Support for skipping past the 'Business PO information' Page when attempting checkout using an Amazon Business Account

### ISSUE THREAD

**Issue by mss-repo** [Hari-Nagarajan/fairgame#417]
Don't really know how to deal with PRs and Branches etc. and publish code to this repo since I'm not a developer. I am pasting the changes I made to /stores/amazon.py below if someone wants to add them to this repo. This allows the Bot to click continue on the Page that shows up prior to Place Order page if you're using an Amazon Business Account. All you have to do is leave the PO field blank and click continue.

In /stores/amazon.py:

Top of the Code (Title of the Page):
-----------------------------------------
```
BUSINESS_PO_TITLES = [
"Business order information"
]
```
-----------------------------------------

Middle of the Code (Identify the Page):
-----------------------------------------
```
elif title in BUSINESS_PO_TITLES:
            self.handle_business_po()
```
-----------------------------------------

Towards the bottom (Routine to handle the Page):
-----------------------------------------
```
@debug
    def handle_business_po(self):
        log.info("On Business PO Page, Trying to move on to checkout")
        button = None
        try:
            button = self.driver.find_element_by_xpath('//*[@id="a-autoid-0"]/span/input')
        except exceptions.NoSuchElementException:
            log.info("Could not find the continue button")
        if button:
            button.click()
        else:
            self.notification_handler.send_notification(
                "Could not click continue button, user intervention required"
            )
            time.sleep(DEFAULT_MAX_WEIRD_PAGE_DELAY)
```
-----------------------------------------

**Comment by DakkJaniels** [comment]
adding this to dev branch.
