### ISSUE TITLE
Amazon Address Error

### ISSUE THREAD

**Issue by A-Din-Djarin** [Hari-Nagarajan/fairgame#424]
When the bot click to checkout, it's redirected to the address selection page. But instantly the bot breaks up and appears an Error. Off course I have read in other previous issues that the 1-Click option may be works to solve this. But it doesn't work for me (Final of this message there is an image showing the 1-Click option of Amazon saying that only works on Kindle and digital purchases).

Here is the screenshot (Addresses in black for privacy):

![screenshot-unknown-title_12-14-2020_10_44_26 - copy](https://user-images.githubusercontent.com/74422931/102109042-a2abf580-3e01-11eb-89bd-5ab6047b04f7.png)

Also here is a copy of the message printed on the console:

2020-12-14 10:43:37 ~~~~~ fairgame[17420] INFO Waiting for home page.
2020-12-14 10:43:40 ~~~~~ fairgame[17420] INFO Already logged in
2020-12-14 10:43:41 ~~~~~ fairgame[17420] INFO Checking stock for items.
2020-12-14 10:43:42 ~~~~~ fairgame[17420] INFO Item in stock and in reserve range!
2020-12-14 10:43:42 ~~~~~ fairgame[17420] INFO clicking add to cart
2020-12-14 10:43:44 ~~~~~ fairgame[17420] INFO clicking checkout.
2020-12-14 10:43:47 ~~~~~ fairgame[17420] ERROR Select a shipping address is not a known title, please create issue indicating the title with a screenshot of page
2020-12-14 10:43:47 ~~~~~ fairgame[17420] ERROR Select a shipping address is not a known title, please create issue indicating the title with a screenshot of page
2020-12-14 10:43:48 ~~~~~ fairgame[17420] ERROR Select a shipping address is not a known title, please create issue indicating the title with a screenshot of page
2020-12-14 10:43:49 ~~~~~ fairgame[17420] ERROR Select a shipping address is not a known title, please create issue indicating the title with a screenshot of page
2020-12-14 10:43:50 ~~~~~ fairgame[17420] ERROR Select a shipping address is not a known title, please create issue indicating the title with a screenshot of page

 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.88

The image of Amazon 1-Click Option:

![Captura de pantalla 2020-12-14 110727](https://user-images.githubusercontent.com/74422931/102108911-7a23fb80-3e01-11eb-8969-cccec617e45f.png)

**Comment by DakkJaniels** [comment]
Do you have a default address and payment set?

**Comment by A-Din-Djarin** [comment]
Yes of course.
There is:

![Captura de pantalla 2020-12-14 121630 - copy](https://user-images.githubusercontent.com/74422931/102112974-78a90200-3e06-11eb-8706-7b56c84adfe7.png)

**Comment by DakkJaniels** [comment]
My page doesn't look like that. When you click 1-click settings, then click back to settings, what does it say your preference is?

**Comment by A-Din-Djarin** [comment]
Ok, I understand. When I do exactly that you said, it looks like this:

![Captura de pantalla 2020-12-14 202345 - copy](https://user-images.githubusercontent.com/74422931/102156248-31913000-3e4b-11eb-8fe1-c92d53d30a65.png)

Squares cover personal data.

**Comment by DakkJaniels** [comment]
What were you trying to buy? It looks like there is an issue with the 5800X.

**Comment by A-Din-Djarin** [comment]
I was trying to buy a RTX 3070, but I lost the opportunity to catch one because of this issue. After that I also tried with other products to make some tests, but same problem. When the bot it's redirected to address page, appears the error.

**Comment by DakkJaniels** [comment]
So your best bet is likely to just delete the other addresses/payments. No eta on fixing this, and might not code a fix anyway, since we wouldn't want to have it ship to unintended locations.

**Comment by A-Din-Djarin** [comment]
Ok, I understand. I'll try that to see if it works.

**Comment by A-Din-Djarin** [comment]
Apparently it's working now. I have tried with other product and now the bot complete the checkout successfully. So, I'm very grateful with you for helping me. Thanks a lot.
And finally, only have to say to everyone that are searching a RTX 3000: I really hope that you and me could catch one soon.

**Comment by mateuszdrab** [comment]
I was playing around with Amazon and after a random addition to basket of an OLED TV, I got the same prompt, no longer though as now it proceeds to the final place your order page. This should be investigated, we can't have the bot fail on drops that happen once a week or less.

**Comment by A-Din-Djarin** [comment]
Yes, I agree. It's something that should be investigated for the future improvements.

**Comment by slider6996** [comment]
I am haing a issue like this, when it adds item to cart it shows only 1 address which is mine but it wants me to select it, bot just hangs there untill i either click the address manually which is the default address or the bot will spit attempt to refresh the page or start over again but it doesnt always work and will just stay stuck on select address, not sure why its doing this.

**Comment by polow** [comment]
> I am haing a issue like this, when it adds item to cart it shows only 1 address which is mine but it wants me to select it, bot just hangs there untill i either click the address manually which is the default address or the bot will spit attempt to refresh the page or start over again but it doesnt always work and will just stay stuck on select address, not sure why its doing this.

Same here, even tho i have shipping bypass option in batch file. It just start counting and not clicking shipping address which is just one address.

**Comment by slider6996** [comment]
> > I am haing a issue like this, when it adds item to cart it shows only 1 address which is mine but it wants me to select it, bot just hangs there untill i either click the address manually which is the default address or the bot will spit attempt to refresh the page or start over again but it doesnt always work and will just stay stuck on select address, not sure why its doing this.
> 
> Same here, even tho i have shipping bypass option in batch file. It just start counting and not clicking shipping address which is just one address.

yup i tried the bypass option too and still a no go.

**Comment by racineda** [comment]
Seeing similar issue. Checkout page is reported as ' ' though so a little different maybe then what OP is seeing?


![Screenshot 2021-02-26 164431](https://user-images.githubusercontent.com/11038661/109363649-aa9d0280-7852-11eb-9287-150849158f27.png)
![Screenshot 2021-02-26 164939](https://user-images.githubusercontent.com/11038661/109363651-ab359900-7852-11eb-99d2-f7155ccc5896.png)

**Comment by slider6996** [comment]
> Seeing similar issue. Checkout page is reported as ' ' though so a little different maybe then what OP is seeing?
> 
> ![Screenshot 2021-02-26 164431](https://user-images.githubusercontent.com/11038661/109363649-aa9d0280-7852-11eb-9287-150849158f27.png)
> ![Screenshot 2021-02-26 164939](https://user-images.githubusercontent.com/11038661/109363651-ab359900-7852-11eb-99d2-f7155ccc5896.png)
> 
> Edit: I only have a single address as I've been following this post and saw that suggestion.

exact issue im having.

**Comment by rcoplien** [comment]
I'm getting the same thing.  Only have 1 address and 1 click on but it can't find button to proceed to check out;.  Screwed me on 3 times for a 3070.  What is the issues?

**Comment by chromaticity** [comment]
have the same issue as @slider6996, even after setting default address/payment.

**Comment by zestay** [comment]
also same issue.. going to let the bot run a few more cycles still maybe just stock issues cause that. tried also swapping to single address only. going to operate bot on cloned amazon account on another  computer to see if same issues. also bot works fine for other products only address issues with the GPUs

**Comment by Joey3Moons** [comment]
Same issue here, I'll holler if i figure it out.

**Comment by alkorolyov** [comment]
> Apparently it's working now. I have tried with other product and now the bot complete the checkout successfully. So, I'm very grateful with you for helping me. Thanks a lot.
> And finally, only have to say to everyone that are searching a RTX 3000: I really hope that you and me could catch one soon.

Hi, how did you manage to fix this? I missed a GPU because of this bug :( 

`2021-04-15 06:20:29,477|0.6.2|DEBUG|Calling navigate_pages(<stores.amazon.Amazon object at 0x0000021666951E50>, False)
2021-04-15 06:20:29,478|0.6.2|DEBUG|Navigating page title: 'Amazon.com Shopping Cart'
2021-04-15 06:20:29,478|0.6.2|DEBUG|Calling handle_cart(<stores.amazon.Amazon object at 0x0000021666951E50>)
2021-04-15 06:20:29,479|0.6.2|INFO|Looking for Proceed To Checkout button...
2021-04-15 06:20:30,163|0.6.2|INFO|Found Checkout Button
2021-04-15 06:20:30,167|0.6.2|INFO|Clicking button
2021-04-15 06:20:30,222|0.6.2|INFO|Button clicked
2021-04-15 06:20:32,344|0.6.2|DEBUG|'handle_cart' returned None
2021-04-15 06:20:32,344|0.6.2|DEBUG|'navigate_pages' returned None
2021-04-15 06:20:32,344|0.6.2|DEBUG|Calling navigate_pages(<stores.amazon.Amazon object at 0x0000021666951E50>, False)
2021-04-15 06:20:32,346|0.6.2|DEBUG|Navigating page title: 'Select a shipping address'
2021-04-15 06:20:32,346|0.6.2|WARNING|Landed on address selection screen.  Fairgame will NOT select an address for you.  Please select necessary options to arrive at the Review Order Page before the next refresh, or complete checkout manually.  You have 30 seconds.`

**Comment by A-Din-Djarin** [comment]
@alkorolyov  I understand you. So I have to tell you and the other guys (really sorry I was gone for so long) that the way I managed to use with the bot worked for me, but the total solution or solution may never exist.

Amazon is too weird. Sometimes the checkout page works fine or sometimes it works poorly. This big problem is more and more common every day and in addition, other people open new topics and have the same problem.

So the way I found it to work is this:

You must have only one delivery address. Also, that address must be the default address in Amazon Smile. Also, you only need one payment method. (Literally like you had)

The next step is testing, and I have to say that a lot.

First, try without the bot and on the web with cheap products. On the page you need to have this:
![image](https://user-images.githubusercontent.com/74422931/114903577-8edac500-9ddc-11eb-97d0-cf6ad8e2e1f3.png)

Try the Buy Now button. If the "Select Address" page appears, don't worry, just select the only address and pay for the order. Yes, that is necessary (and that is the reason for a cheap product. Then you can cancel the order) because if you do, the Amazon algorithm maintains that form to make the payment.

The next step is to repeat the same process. But, at this point, it should redirect you directly from the Buy Now button to the checkout page. If that happens, again, checkout that order. If it redirects you to the page address again, try other products.

After that, try the bot, selecting a really cheap item. But again, the product must have this:
![image](https://user-images.githubusercontent.com/74422931/114904639-afefe580-9ddd-11eb-933b-0a50d24ec046.png)

And test. If it works fine, you can put whatever Ampere GPU code you want.

Another tip is not to buy anything from that amazon account while grabbing a GPU for the same reason. If you buy a product that coincidentally is not sold directly by amazon, the algorithm that saves the steps for the checkout can be damaged, and it is likely that you will have to start over.

That's the way that worked for me, and really hope that works for everyone.

**Comment by DakkJaniels** [comment]
Thanks @A-Din-Djarin. I'll have to update the readme with some of these additional steps/checks and info, but the readme does state (now) that people need to confirm that the bot can make to placing an order *without* it asking for address, and if it *does* ask for address, to purchase an item using the bot's browser. This is similar to what you have, but I'll make some notes about the Buy It Now and purchasing from Amazon.

I'll also note that even if all of this is done, Amazon appears to bug out when items are out of stock and ask for the address to be selected, even though it doesn't matter. I spent 30 minutes or so one night just clicking Use this Address and it would either take me to an empty cart page, or back to the home page with nothing in cart, or the item would still be in cart, but proceeding to checkout always asked for address again and I could never confirm the address, it would always error out manually.

**Comment by A-Din-Djarin** [comment]
Ok @DakkJaniels I understand.
Thanks for your feedback. 
Kind regards.
