### ISSUE TITLE
Checking for stock items

### ISSUE THREAD

**Issue by edilier03** [Hari-Nagarajan/fairgame#425]
I get no errors and when trying to purchase the USB it goes to the correct ASIN but it just doesn't buy it

**Comment by edilier03** [comment]
it keeps saying "checking for stock" but there is actually stock :/

**Comment by DakkJaniels** [comment]
Post something that can help us diagnose the issue (screenshots, logs, your amazon_config, etc.). What you've posted is not helpful.

**Comment by edilier03** [comment]
{
  "asin_groups": 1,
  "asin_list_1": ["B07TX8FY6W"],
  "reserve_min_1": 10,
  "reserve_max_1": 30,
  "amazon_website": "smile.amazon.com"
}

![image](https://user-images.githubusercontent.com/38407112/102155164-f8f05700-3e48-11eb-968d-ee4286452c5c.png)

![image](https://user-images.githubusercontent.com/38407112/102155201-0dccea80-3e49-11eb-8364-0937022606ce.png)


That is all it does.. it does not buy the USB :/

**Comment by DakkJaniels** [comment]
Closing. You set the minimum price to $10. The price of the item is $7.94.

**Comment by edilier03** [comment]
Dang!!
Thanks! sorry!
