### ISSUE TITLE
Failed to get the URL, were in the exception now

### ISSUE THREAD

**Issue by nelson-wu** [Hari-Nagarajan/fairgame#426]
**Describe the bug**
This error shows up on long running instances when presumably OS suspends chrome. Chrome tab shows blank page. Bot repeatedly shows this error and cannot refresh page.

**To Reproduce**
Not sure how to repro manually. Show up randomly for long running sessions.

**Screenshots**
![image](https://user-images.githubusercontent.com/16801046/102186871-1c76ca00-3e68-11eb-869a-579394558959.png)

**Desktop (please complete the following information):**
 - OS: Win10 20H2
 - Browser: Chrome 
 - Version  87.0.4280.88

**Comment by ardydavari** [comment]
I have the same error:

![image](https://user-images.githubusercontent.com/10945153/102362878-ba05f280-3f69-11eb-8d7a-3bd9359c4271.png)

I think this is the responsible code block:
https://github.com/Hari-Nagarajan/fairgame/blob/5e0f60f39dedf02ff6bec9a1131d6ea24c8553ec/stores/amazon.py#L446


    OS: Manjaro Linux VM
    Browser: Chromium 87.0.4280.66 (Official Build) Arch Linux

**Comment by DakkJaniels** [comment]
Restart your bot at least every 24 hours to avoid having this issue (or more frequently if you are running on poor specs).

**Comment by TilakPatel** [comment]
Having this same issue, except it happens for me after running the script for only 15 minutes. Im on Ubuntu linux 20.04.

**Comment by TilakPatel** [comment]
Resolved it by just closing other programs..dont know if theres much that can be done as the program suspension is done on an OS level

**Comment by johnpyp** [comment]
Why not restart the chromium instance when that happens? I'm pretty sure streetmerchant does that with puppeteer. Though, it's not an ideal solution when running in non-headless mode.

**Comment by DakkJaniels** [comment]
Where the exception occurs, it could also be because the page just didn't load. Trying to determine the best way to handle, but restarting bot because the page didn't load is not the right way, unless we want to see complaints from people about their bot restarting and missing a drop.

**Comment by TilakPatel** [comment]
> Why not restart the chromium instance when that happens? I'm pretty sure streetmerchant does that with puppeteer. Though, it's not an ideal solution when running in non-headless mode.
> 
> This has definitely been an annoying issue for me. It could be nice to have an option to kill the process when it happens so it can be restarted by another tool like pm2, but that hits the issue of having to enter the password manually for the credentials.

I think we could possibly get around this by being able to run the script with a -p option thats lets the user enter the password so the prompt doesnt come up.

**Comment by DakkJaniels** [comment]
Should be resolved in 0.5.0
