### ISSUE TITLE
ASIN blocked from Bulk adding by Amazon

### ISSUE THREAD

**Issue by felodelavallet** [Hari-Nagarajan/fairgame#427]
**Describe the bug**
When I add the ASIN number and Start the Bot,i get this message. 

The bot only works for AMD graphics cards.

Any solution for NVIDIA Graphics Cards?

![315BA25A-03FE-4B11-A883-C00B2C42DE30](https://user-images.githubusercontent.com/74694273/102255016-72368b00-3ed7-11eb-85e1-0954250ed261.jpeg)

**Comment by DakkJaniels** [comment]
Your program is at least a month old
