### ISSUE TITLE
Any chance for newegg update / auto checkout? 

### ISSUE THREAD

**Issue by dalumberjack03** [Hari-Nagarajan/fairgame#430]
I have seen others that also seem to avoid newegg. Not sure if there is a reason or not, but would love support for the site.
Thank you for all your hard work!

**Comment by DakkJaniels** [comment]
No, this is unlikely to be added to this repo any time soon. Someone posted this to the Discord if you want to try this out: https://github.com/MrTpat/newegg-bot-public
