### ISSUE TITLE
Make fairgame return to searching a product when cart empty at checkout

### ISSUE THREAD

**Issue by Amtrix** [Hari-Nagarajan/fairgame#432]
Fairgame may encounter the scenario where there is a matching product listed but someone has already been faster and bought it. In this case, when fairgame tries to add the item to the cart, it will think it succeeded and progress to checkout. There it will find that the cart is empty after all and get stuck in a loop.

**Comment by DakkJaniels** [comment]
It does return to product search already. Can you send a screenshot of the terminal? It still tries to checkout a few times, should be 3, but then returns to checking stock.

**Comment by Amtrix** [comment]
Oh, my bad. Checked the logs and it fits with what you're saying. It would be nice if it was possible to make the "--delay" parameter only affect checking for the item while another parameter (for example, "--delay-checkout") to affect the navigation at checkout. Might look into this myself. Different issue -- closing this. Thank you!

**Comment by DakkJaniels** [comment]
No worries. ---delay actually only effects the checking of items. During checkout, there are some built in manual delays, but I'm trying to adjust code now to eliminate them.
