### ISSUE TITLE
Couldn't find button to proceed to checkout

### ISSUE THREAD

**Issue by EbenMK** [Hari-Nagarajan/fairgame#439]
![faterror](https://user-images.githubusercontent.com/13169489/103036195-2e76fd80-4537-11eb-8722-815c3f59a3f9.JPG)

Every time the bot tries to checkout I get this error, is this an issue with the bot or is the item just going out of stock too quickly?

**Comment by DakkJaniels** [comment]
what does the browser look like at the time?

**Comment by chadaradinski** [comment]
I believe this error occurs when Amazon directs you to a page asking if you'd like a special offer of Amazon Prime. This seems to happen once per day for me.

**Comment by Naoki95957** [comment]
I had this issue with the test item. Enabling slow mode helped it. I noticed when it initially clicks proceed to checkout there is a brief loading portion where the button is grayed out.
