### ISSUE TITLE
running log removed in 0.5.3?

### ISSUE THREAD

**Issue by silentreply** [Hari-Nagarajan/fairgame#441]
Unless there is some negative impact on performance I would prefer if the continuous log was present as in v5.0.2. Was it intended to be removed in v0.5.3?

v0.5.2:
![image](https://user-images.githubusercontent.com/59859911/103041155-929fbe80-4543-11eb-83dd-2e26413888d1.png)

v0.5.3:
![image](https://user-images.githubusercontent.com/59859911/103041196-ad723300-4543-11eb-9964-fe1140cc21e9.png)

**Comment by DakkJaniels** [comment]
You were getting errors in terminal. We fixed the bug.

**Comment by silentreply** [comment]
@DakkJaniels Hmm..I actually prefer if those errors are present since it allows confirmation that the pages are being refreshed and you can see the actual delay between refresh. Is there a simple way I could enable them?

**Comment by DakkJaniels** [comment]
add something that logs to terminal after check_stock() finishes, not going to include that in release, and not going to make errors pop up on purpose.

**Comment by silentreply** [comment]
Ok thanks!
