### ISSUE TITLE
EU-support broken (fix described within) - Failed to load Page

### ISSUE THREAD

**Issue by ThermoTony** [Hari-Nagarajan/fairgame#443]
The bot cant load the pages in the 3sec. intervall. it will load the tabs in chrome however, the messages that he cant load the pages are flooding the cmd window.

I did a fresh install of the bot and python, but the error persisted.

![Unbenannt](https://user-images.githubusercontent.com/76541643/103051859-0bc90100-4598-11eb-935f-0486e020ed6b.jpg)

im Running:
Windows 10 Education Version 20H2
Browser used by the bot is Chrome(Version 87.0.4280.88)

Also before updating the bot to the newest Version i didnt had that Message show up.

**Comment by DakkJaniels** [comment]
You have to add the message that is appearing on the page to the ```NO_SELLERS``` list, like the following. Only the english sites were added right now, will add international sites in later update: 
![image](https://user-images.githubusercontent.com/6080734/103058179-87fb1e80-456f-11eb-82be-575a41da0c70.png)

**Comment by ThermoTony** [comment]
awesome! works just fine now ^^ 
thank you very much

**Comment by DakkJaniels** [comment]
Leaving this open until hotfix is released.
