### ISSUE TITLE
error popping randomly since 0.5.3 update

### ISSUE THREAD

**Issue by gregoiredelzongle** [Hari-Nagarajan/fairgame#448]
I'm looking for a PS5 in Amazon France, things was working as intended but new version added this error popping randomly for a few hours each day. 

```
2020-12-25 06:06:26 DESKTOP-CEON2GG fairgame[265560] ERROR page did not change

2020-12-25 06:06:36 DESKTOP-CEON2GG fairgame[265560] INFO failed to load page for B08H93ZRK9, going to next ASIN
```
repeated a few hundred times.

The log file seems bloated too with a whoping 1.2gb file after running it for one day.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 0.5.3

**Comment by gregoiredelzongle** [comment]
![log](https://user-images.githubusercontent.com/9194561/103130524-4b2d4580-469d-11eb-9afe-0c1d6b64eb8e.jpg)

The new script seems to log a very long javascript script each times it looks for available stock

**Comment by DakkJaniels** [comment]
repeat of #443

**Comment by gregoiredelzongle** [comment]
I’ve already did the changes adviced in #443  but got the errors anyways (also the bloated log).

**Comment by DakkJaniels** [comment]
logging issue will be fixed in next update.   What is happening on your screen (browser) when the error happens?

**Comment by gregoiredelzongle** [comment]
The issues are resolved with the latest update. Many thanks !
