### ISSUE TITLE
shipping options page exception

### ISSUE THREAD

**Issue by highport** [Hari-Nagarajan/fairgame#450]
When attempting a test purchase to confirm the bot is working, a small purchase fails during checkout attempt at a "Select Shipping Options" page. Tried to handle this with using the "--shipping-bypass" option. This has some success and allows for the shipping options page to be navigated past, but fails on the next page because for some reason Amazon wants you to pick shipping info yet again. This page is called "Select Shipping Options".

details on execution:

- launched via _Amazon.bat using: cmd /k pipenv run python app.py amazon --shipping-bypass --delay=5
- using smile.amazon.com
- not a prime member
- last updated 12/24/20 from master

https://imgur.com/VD35fuY
https://imgur.com/5VnjbKu

**Comment by DakkJaniels** [comment]
I messaged you on Discord.

**Comment by highport** [comment]
inspected the element for the "Continue" button. Pulled this code:
```
<div class="a-box-inner">
    <span class="sosp-continue-button a-button a-button-primary a-button-span12 a-padding-none  continue-button">
      <span class="a-button-inner">
        <input type="submit" class="a-button-text" value="Continue" data-testid="">
      </span>
    </span>
    <span class="continue-button-blocker a-button a-button-primary a-button-disabled a-button-span12 a-padding-none no-js-hide  aok-hidden">
      <span class="a-button-inner">
        <input class="a-button-text a-declarative" data-action="a-button-blocker" data-a-button-blocker="{&quot;type&quot;:&quot;text&quot;}" data-blocker-text="" value="Continue" type="submit">
      </span>
    </span>
    <span class="continue-button-blocker-text a-text-beside-button"></span>
  </div>
```

**Comment by highport** [comment]
The next page has yet another "Continue" button for shipping information

```
<input name="ppw-widgetEvent:SetPaymentPlanSelectContinueEvent" class="a-button-input a-button-text" type="submit" aria-labelledby="pp-1Povbi-85-announce">
```

https://imgur.com/VOok7zw

**Comment by highport** [comment]
yet another page, this time ambushing for a chance to sell you Prime:

```
<a href="/gp/buy/prime/handler.html/ref=prime_pdp_ho_nt_sov?subscriptionplanID=0P93105668&amp;redirectPath=%2Fgp%2Fprime%2Fpip%2Fproceed.html&amp;ie=UTF8&amp;action.checkoutInterstitialDecline=1&amp;eventCode=105" class="prime-nothanks-button prime-checkout-continue-link primeEvent checkout-continue-link a-button-text" rel="nt1" data-max-prefetches="1">
                                            No thanks, I do not want FREE delivery
                                        </a>
```

https://imgur.com/PfjHIQO

**Comment by highport** [comment]
final page for checkout. I'm assuming that the app handles this page well, but haven't had the chance to get this far. Just in case, here's the checkout button element and screen:
```
<input title="Place your order" class="a-button-text place-your-order-button" value="Place your order" name="placeYourOrder1" type="submit" data-testid="">
```

https://imgur.com/Gefv5hj

**Comment by guy-frost** [comment]
I now have the same page "Select a shipping address" that's being forced before each checkout. This has been validated for multiple purchase attempts with 0 success. 

My page is slightly different than @highport's. Instead of a 'Continue' button, my page has a 'Deliver to this address' button. Screenshot below.

Error log:
DEBUG: "2021-01-29 11:39:36,547 - Calling navigate_pages(<stores.amazon.Amazon object at 0x0000015EF2088970>, False)
DEBUG: "2021-01-29 11:39:36,564 - title is: [Select a shipping address]
WARNING: "2021-01-29 11:39:39,565 - FairGame is not sure what page it is on - will attempt to resolve.
ERROR: "2021-01-29 11:39:39,607 - Select a shipping address is not a known title, please create issue indicating the title with a screenshot of page

I'm using the latest Xpath branch. Confirmed that 'Select a shipping address' is within the 'ADDRESS_SELECT' list within fairgame.conf 

![screenshot-unknown-title_01-29-2021_11_39_39](https://user-images.githubusercontent.com/78267205/106359601-5f3a1780-62d9-11eb-8570-94f09dd26170.jpg)

**Comment by guy-frost** [comment]
HTML in ZIP 
[unknown-title_source_01-29-2021_11_39_39_edit.zip](https://github.com/Hari-Nagarajan/fairgame/files/5898354/unknown-title_source_01-29-2021_11_39_39_edit.zip)

**Comment by felodelavallet** [comment]
I have the same problem, with Asus strix 3080 and EVGA FTW3 3080 drop Miss.

:(

![68D495B5-D90F-42B1-90A0-95ED1350A4CD](https://user-images.githubusercontent.com/74694273/106368229-1a80a180-6316-11eb-9c7e-bc51a7ee591b.jpeg)
![BB4AAE0F-29AB-4F11-A043-91CCC4AC932B](https://user-images.githubusercontent.com/74694273/106368231-1ce2fb80-6316-11eb-97be-9b74ec05ab06.jpeg)

**Comment by forcefed** [comment]
> I have the same problem, with Asus strix 3080 and EVGA FTW3 3080 drop Miss.
> 
> :(
> 
> ![68D495B5-D90F-42B1-90A0-95ED1350A4CD](https://user-images.githubusercontent.com/74694273/106368229-1a80a180-6316-11eb-9c7e-bc51a7ee591b.jpeg)
> ![BB4AAE0F-29AB-4F11-A043-91CCC4AC932B](https://user-images.githubusercontent.com/74694273/106368231-1ce2fb80-6316-11eb-97be-9b74ec05ab06.jpeg)



> I now have the same page "Select a shipping address" that's being forced before each checkout. This has been validated for multiple purchase attempts with 0 success.
> 
> My page is slightly different than @highport's. Instead of a 'Continue' button, my page has a 'Deliver to this address' button. Screenshot below.
> 
> Error log:
> DEBUG: "2021-01-29 11:39:36,547 - Calling navigate_pages(<stores.amazon.Amazon object at 0x0000015EF2088970>, False)
> DEBUG: "2021-01-29 11:39:36,564 - title is: [Select a shipping address]
> WARNING: "2021-01-29 11:39:39,565 - FairGame is not sure what page it is on - will attempt to resolve.
> ERROR: "2021-01-29 11:39:39,607 - Select a shipping address is not a known title, please create issue indicating the title with a screenshot of page
> 
> ![screenshot-unknown-title_01-29-2021_11_39_39](https://user-images.githubusercontent.com/78267205/106359601-5f3a1780-62d9-11eb-8570-94f09dd26170.jpg)

You guys need to add --shipping-bypass to the _amazon.bat file to bypass that page, the issue the highport is having is on the next page, and i'm having it too. Would be so much easier if the bot used buy now rather than going through the cart and shipping options.

**Comment by DakkJaniels** [comment]
1. If you set things up correctly, as written in the readme directions, it doesn't go through shipping options
2. Please program the changes to use buy it now then
