### ISSUE TITLE
Time Import Error, Module Not Found Error, Playsound

### ISSUE THREAD

**Issue by magmar01** [Hari-Nagarajan/fairgame#451]
C:\Users\Username\Documents\GitHub\fairgame\notifications\notifications.py", line 4, in <module>
    from playsound import playsound
ModuleNotFoundError: No module named 'playsound

File "app.py", line 1, in <module>
    from cli import cli
  File "C:\Users\Username\Documents\GitHub\fairgame\cli\cli.py", line 17, in <module>
    from notifications.notifications import NotificationHandler, TIME_FORMAT

**Comment by DakkJaniels** [comment]
did you `pipenv shell` `pipenv install`?

**Comment by magmar01** [comment]
> did you `pipenv shell` `pipenv install`?

yes I did, while in github directory on fairgame in command prompt

**Comment by lbux** [comment]
Getting the same error for playsound and apprise. Depending on what is first in notficiations.py it will throw an error when trying to import the modules from the packages regardless of how many times I try to reinstall using `pipenv install`.

PS C:\Users\lb\fairgame> pipenv run app.py amazon -disable-presence
Traceback (most recent call last):
  File "C:\Users\lb\fairgame\app.py", line 1, in <module>
    from cli import cli
  File "C:\Users\lb\fairgame\cli\cli.py", line 17, in <module>
    from notifications.notifications import NotificationHandler, TIME_FORMAT
  File "C:\Users\lb\fairgame\notifications\notifications.py", line 4, in <module>
    from playsound import playsound
ModuleNotFoundError: No module named 'playsound'


PS C:\Users\lb\fairgame> pipenv run app.py amazon -disable-presence
Traceback (most recent call last):
  File "C:\Users\lb\fairgame\app.py", line 1, in <module>
    from cli import cli
  File "C:\Users\lb\fairgame\cli\cli.py", line 17, in <module>
    from notifications.notifications import NotificationHandler, TIME_FORMAT
  File "C:\Users\lb\fairgame\notifications\notifications.py", line 4, in <module>
    import apprise
ModuleNotFoundError: No module named 'apprise'

![image](https://user-images.githubusercontent.com/30765968/104262328-3f32d900-543c-11eb-959c-79570bd4d2c6.png)

**Comment by lbux** [comment]
So, some new info.

Running `python app.py amazon` works fine if running within the shell environment, as expected. However, the above stated issue still occurs when trying to run `pipenv run app.py amazon` to bypass having to run `pipenv shell` beforehand.

@magmar01 how did you try to run the script?
