### ISSUE TITLE
Run Amazon script when logged off

### ISSUE THREAD

**Issue by liangjuc** [Hari-Nagarajan/fairgame#458]
Hi guys, I noticed amazon will soft ban the account when this script refresh the page at a fixed rate (3-5s). 

Just wondering if anyone have tried to modify the script so that it monitors the Amazon offer listing page as an unrecognized customer (i.e. amazon account logged off), and when the add to cart button appears, it auto enters your amazon account credential upon the add-to-cart button click and checkout for you? Thx

**Comment by liangjuc** [comment]
closing as this can be done by commenting out the initial log in on the script

**Comment by Steccas** [comment]
Yet this is a great idea and that's how it should be done!

**Comment by DakkJaniels** [comment]
good luck responding to captcha or 2FA fast enough to get it, when it finds something in stock!

**Comment by Steccas** [comment]
Sigh

**Comment by gtrak** [comment]
You can disable 2FA for your account. It would be nice if we didn't have to, but I haven't run into these issues when doing so.
