### ISSUE TITLE
INFO: Failed to load prices

### ISSUE THREAD

**Issue by mh1ger** [Hari-Nagarajan/fairgame#461]
![grafik](https://user-images.githubusercontent.com/77031464/103713929-bf30ed00-4fbd-11eb-8723-73297640a635.png)

Hi, was trying to test buy a cooking pan, login works but then i get error: Failed to load prices. Tried different ASINs, happens all the time....

Any solutions?

Regards

**Comment by DakkJaniels** [comment]
domain?

**Comment by mh1ger** [comment]
Sorry, forgot to mention.

smile.amazon.de

**Comment by DakkJaniels** [comment]
Closing, this is a duplicate of Issue #460
