### ISSUE TITLE
'PIL' module not found

### ISSUE THREAD

**Issue by antonioh501** [Hari-Nagarajan/fairgame#471]
First of all I'm sorry but I am the greatest noob you can find on Earth so, if anybody is eager to help, please be kind.
I'm on a RPi 4 with Raspbian installed... I managed to follow all the steps but at the very end I got the following error:

```
(fairgame) pi@raspberrypi:~/fairgame $ python app.py
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from cli import cli
  File "/home/pi/fairgame/cli/cli.py", line 18, in <module>
    from stores.amazon import Amazon
  File "/home/pi/fairgame/stores/amazon.py", line 12, in <module>
    from amazoncaptcha import AmazonCaptcha
  File "/home/pi/.local/share/virtualenvs/fairgame-3Td2oUte/lib/python3.8/site-packages/amazoncaptcha/__init__.py", line 42, in <module>
    from .solver import AmazonCaptcha
  File "/home/pi/.local/share/virtualenvs/fairgame-3Td2oUte/lib/python3.8/site-packages/amazoncaptcha/solver.py", line 18, in <module>
    from .utils import cut_the_white, merge_horizontally, find_letter_boxes
  File "/home/pi/.local/share/virtualenvs/fairgame-3Td2oUte/lib/python3.8/site-packages/amazoncaptcha/utils.py", line 10, in <module>
    from PIL import Image, ImageChops
ModuleNotFoundError: No module named 'PIL'
```
Can somebody help me understand the reason I got this and what I could do to solve it? Thank you

**Comment by DakkJaniels** [comment]
you don't have a module named PIL. You need to install it.

**Comment by antonioh501** [comment]
Thank you for your reply. I looked better thru the steps and when executing:
`pipenv install`
it ends with the following:
`An error occurred while installing pillow==7.2.0; python_version >= '3.5'` followed by a screen of install error. Any guess?

**Comment by DakkJaniels** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=79379

maybe? 
![image](https://user-images.githubusercontent.com/6080734/105413937-ce8e7800-5c04-11eb-8562-e185deda8f21.png)

**Comment by antonioh501** [comment]
Unfortunately I got no luck.. I'll just quit trying. I think that my knowledge is still too little to achieve anything. Thanks for helping anyway

**Comment by tomprsn** [comment]
I'm just setting this up on my Raspberry Pi now as well and had the same problem. 

This worked for me: 
`sudo apt install python3-dev libjpeg8-dev libpng-dev libfreetype6-dev`

From: https://stackoverflow.com/questions/54496599/pip-cant-install-pillow

**Comment by antonioh501** [comment]
Thanks @tomprsn this solved my issue!
