### ISSUE TITLE
Add to FAQ

### ISSUE THREAD

**Issue by matsojr22** [Hari-Nagarajan/fairgame#473]
As far as I am aware, Amazon has never really had RTX 30 series stock outside resellers. Might be worth adding to the FAQ for the people who are trying to get GPUs.

I could be wrong, but my searching says the last time they may have had stock was possibly November. Don't want to discourage anyone, but we might be generating a lot of traffic for nothing if that is the SKU you are after.

**Comment by DakkJaniels** [comment]
You are wrong - many people have posted in discord indicating that the bot has purchased a RTX 30 series for them.

**Comment by matsojr22** [comment]
Right on, just trying to be helpful as my research indicated otherwise.

**Comment by DakkJaniels** [comment]
Not sure where you are doing your research, but, for example:
![image](https://user-images.githubusercontent.com/6080734/105803513-a8056f80-5f6b-11eb-9689-36524cf1e957.png)
![image](https://user-images.githubusercontent.com/6080734/105803644-e864ed80-5f6b-11eb-9549-33c0988997a6.png)

**Comment by matsojr22** [comment]
Previously Reddit.

I’ll check out the discord. Again, not trying to shit on your work. I’ve
had several iterations of Fairgame running various asin’s for a while now
with no luck and saw some threads suggesting Amazon was not natively
stocking.

Obviously based on the discord that is incorrect. I’m glad to see people
having success against the scalpers.

Thanks,
M
