### ISSUE TITLE
Bot trying to buy another item i dont want to buy

### ISSUE THREAD

**Issue by megalomenyak** [Hari-Nagarajan/fairgame#496]
20 minutes ago bot find an item. But cannot bought it. because clicking add to cart for another seller and for out of my reserve range.  it happned couple of times now. Why is that?

INFO: "2021-02-09 16:00:35,065 - Item in stock and in reserve range!
INFO: "2021-02-09 16:00:35,068 - clicking add to cart
DEBUG: "2021-02-09 16:00:35,250 - Failed reconnect attempt. Pipe Not Found - Is Discord Running?
INFO: "2021-02-09 16:00:35,828 - did not add to cart, trying again
DEBUG: "2021-02-09 16:00:35,830 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:00:35,838 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=1)
INFO: "2021-02-09 16:00:36,511 - Item in stock and in reserve range!
INFO: "2021-02-09 16:00:36,511 - clicking add to cart
INFO: "2021-02-09 16:00:37,306 - did not add to cart, trying again
DEBUG: "2021-02-09 16:00:37,307 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:00:37,312 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=2)
INFO: "2021-02-09 16:00:38,132 - Item in stock and in reserve range!
INFO: "2021-02-09 16:00:38,133 - clicking add to cart
INFO: "2021-02-09 16:00:39,012 - did not add to cart, trying again
DEBUG: "2021-02-09 16:00:39,015 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:00:39,021 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=3)
DEBUG: "2021-02-09 16:00:39,021 - Failed reconnect attempt. Pipe Not Found - Is Discord Running?
INFO: "2021-02-09 16:00:39,846 - Item in stock and in reserve range!
INFO: "2021-02-09 16:00:39,847 - clicking add to cart
INFO: "2021-02-09 16:00:40,656 - did not add to cart, trying again
DEBUG: "2021-02-09 16:00:40,659 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:00:40,666 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=4)
INFO: "2021-02-09 16:00:40,666 - max add to cart retries hit, returning to asin check
DEBUG: "2021-02-09 16:00:40,666 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:40,666 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:40,666 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:40,666 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:40,666 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:42,666 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, 'B08HN6KYS3', 750.0, 1000.0)
DEBUG: "2021-02-09 16:00:43,184 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:45,185 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, 'B08M13DXSZ', 600.0, 751.0)
DEBUG: "2021-02-09 16:00:45,757 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:47,758 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, 'B08LLG9KQT', 380.0, 750.0)
INFO: "2021-02-09 16:00:48,714 - Item in stock and in reserve range!
INFO: "2021-02-09 16:00:48,715 - clicking add to cart
DEBUG: "2021-02-09 16:00:48,855 - Failed reconnect attempt. Pipe Not Found - Is Discord Running?
INFO: "2021-02-09 16:00:49,470 - did not add to cart, trying again
DEBUG: "2021-02-09 16:00:49,473 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:00:49,479 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=1)
INFO: "2021-02-09 16:00:50,364 - Item in stock and in reserve range!
INFO: "2021-02-09 16:00:50,365 - clicking add to cart
INFO: "2021-02-09 16:00:51,070 - did not add to cart, trying again
DEBUG: "2021-02-09 16:00:51,074 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:00:51,093 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=2)
INFO: "2021-02-09 16:00:51,785 - Item in stock and in reserve range!
INFO: "2021-02-09 16:00:51,785 - clicking add to cart
INFO: "2021-02-09 16:00:52,394 - did not add to cart, trying again
DEBUG: "2021-02-09 16:00:52,397 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:00:52,403 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=3)
DEBUG: "2021-02-09 16:00:52,404 - Failed reconnect attempt. Pipe Not Found - Is Discord Running?
INFO: "2021-02-09 16:00:53,276 - Item in stock and in reserve range!
INFO: "2021-02-09 16:00:53,277 - clicking add to cart
INFO: "2021-02-09 16:00:54,055 - did not add to cart, trying again
DEBUG: "2021-02-09 16:00:54,059 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:00:54,063 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=4)
INFO: "2021-02-09 16:00:54,063 - max add to cart retries hit, returning to asin check
DEBUG: "2021-02-09 16:00:54,064 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:54,064 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:54,064 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:54,064 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:54,064 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:56,065 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, 'B08HN6KYS3', 750.0, 1000.0)
DEBUG: "2021-02-09 16:00:57,697 - 'check_stock' returned False
DEBUG: "2021-02-09 16:00:59,699 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, 'B08M13DXSZ', 600.0, 751.0)
DEBUG: "2021-02-09 16:01:00,245 - 'check_stock' returned False
DEBUG: "2021-02-09 16:01:02,245 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, 'B08LLG9KQT', 380.0, 750.0)
INFO: "2021-02-09 16:01:05,739 - Item in stock and in reserve range!
INFO: "2021-02-09 16:01:05,740 - clicking add to cart
DEBUG: "2021-02-09 16:01:05,858 - Failed reconnect attempt. Pipe Not Found - Is Discord Running?
INFO: "2021-02-09 16:01:06,631 - did not add to cart, trying again
DEBUG: "2021-02-09 16:01:06,635 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:01:06,641 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=1)
INFO: "2021-02-09 16:01:07,313 - Item in stock and in reserve range!
INFO: "2021-02-09 16:01:07,314 - clicking add to cart
INFO: "2021-02-09 16:01:08,138 - did not add to cart, trying again
DEBUG: "2021-02-09 16:01:08,146 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:01:08,153 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=2)
INFO: "2021-02-09 16:01:08,935 - Item in stock and in reserve range!
INFO: "2021-02-09 16:01:08,935 - clicking add to cart
INFO: "2021-02-09 16:01:09,810 - did not add to cart, trying again
DEBUG: "2021-02-09 16:01:09,813 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:01:09,818 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=3)
DEBUG: "2021-02-09 16:01:09,818 - Failed reconnect attempt. Pipe Not Found - Is Discord Running?
DEBUG: "2021-02-09 16:01:10,458 - 'check_stock' returned False
DEBUG: "2021-02-09 16:01:10,458 - 'check_stock' returned False
DEBUG: "2021-02-09 16:01:10,458 - 'check_stock' returned False
DEBUG: "2021-02-09 16:01:10,458 - 'check_stock' returned False
DEBUG: "2021-02-09 16:01:12,459 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, 'B08HN6KYS3', 750.0, 1000.0)
DEBUG: "2021-02-09 16:01:12,995 - 'check_stock' returned False
DEBUG: "2021-02-09 16:01:14,995 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, 'B08M13DXSZ', 600.0, 751.0)
DEBUG: "2021-02-09 16:01:15,863 - 'check_stock' returned False
DEBUG: "2021-02-09 16:01:17,864 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, 'B08LLG9KQT', 380.0, 750.0)
INFO: "2021-02-09 16:01:18,600 - Item in stock and in reserve range!
INFO: "2021-02-09 16:01:18,601 - clicking add to cart
INFO: "2021-02-09 16:01:19,407 - did not add to cart, trying again
DEBUG: "2021-02-09 16:01:19,412 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:01:19,434 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=1)
DEBUG: "2021-02-09 16:01:19,435 - Failed reconnect attempt. Pipe Not Found - Is Discord Running?
INFO: "2021-02-09 16:01:20,324 - Item in stock and in reserve range!
INFO: "2021-02-09 16:01:20,325 - clicking add to cart
INFO: "2021-02-09 16:01:21,110 - did not add to cart, trying again
DEBUG: "2021-02-09 16:01:21,114 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:01:21,127 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=2)
INFO: "2021-02-09 16:01:21,752 - Item in stock and in reserve range!
INFO: "2021-02-09 16:01:21,752 - clicking add to cart
INFO: "2021-02-09 16:01:22,734 - did not add to cart, trying again
DEBUG: "2021-02-09 16:01:22,747 - failed title was AmazonSmile Basket
DEBUG: "2021-02-09 16:01:22,763 - Calling check_stock(<stores.amazon.Amazon object at 0x0000014417BDA7F0>, asin='B08LLG9KQT', reserve_max=750.0, reserve_min=380.0, retry=3)
INFO: "2021-02-09 16:01:23,517 - Item in stock and in reserve range!
INFO: "2021-02-09 16:01:23,517 - clicking add to cart

**Comment by DakkJaniels** [comment]
You probably need to add "AmazonSmile Basket" to the list of SHOPING_CART_TITLES.
