### ISSUE TITLE
Failing to load pages, running very slowly

### ISSUE THREAD

**Issue by NeighborWithSugar** [Hari-Nagarajan/fairgame#502]
Page takes almost 5-8 seconds in between loading, and it skips ASINs sometimes, but at a later time it works.

Amazon.bat
cmd /k pipenv run python app.py amazon  --no-image  --single-shot  --no-screenshots  --checkshipping  --p (password)  --disable-presence

Config File
{
  "asin_groups": 12,
  "asin_list_1": ["B08L8LG4M3"],
  "reserve_min_1": 499,
  "reserve_max_1": 650,
  "asin_list_2": ["B08KWPDXJZ"],
  "reserve_min_2": 499,
  "reserve_max_2": 650,
  "asin_list_3": ["B08L8L71SM"],
  "reserve_min_3": 499,
  "reserve_max_3": 650,
  "asin_list_4": ["B08KY266MG"],
  "reserve_min_4": 499,
  "reserve_max_4": 650,
  "asin_list_5": ["B08WC3FKQ9"],
  "reserve_min_5": 499,
  "reserve_max_5": 650,
  "asin_list_6": ["B08WC3FKQ9"],
  "reserve_min_6": 499,
  "reserve_max_6": 650,  
  "asin_list_7": ["B08HBJB7YD"],
  "reserve_min_7": 499,
  "reserve_max_7": 650,
  "asin_list_8": ["B08L8KC1J7"],
  "reserve_min_8": 499,
  "reserve_max_8": 650,
  "asin_list_9": ["B08V3MM48M"],
  "reserve_min_9": 499,
  "reserve_max_9": 650,
  "asin_list_10": ["B08M14Y3C7"],
  "reserve_min_10": 499,
  "reserve_max_10": 650,
  "asin_list_11": ["B08TGLK6T4"],
  "reserve_min_11": 499,
  "reserve_max_11": 650,
  "asin_list_12": ["B08W7ZRD3V"],
  "reserve_min_12": 499,
  "reserve_max_12": 650,
  "amazon_website": "smile.amazon.com"
}

![image](https://user-images.githubusercontent.com/78927493/107810605-f58b2600-6d3a-11eb-9531-a4b6cd4022d3.png)

**Comment by gtrak** [comment]
Not sure if it matters for your issue, but since those are all the same price, you could make the config a lot shorter by putting all the asins in one list.

 "asin_list_1": ["B08L8LG4M3","B08KWPDXJZ","B08L8L71SM",...],

**Comment by NeighborWithSugar** [comment]
> Not sure if it matters for your issue, but since those are all the same price, you could make the config a lot shorter by putting all the asins in one list.
> 
> "asin_list_1": ["B08L8LG4M3","B08KWPDXJZ","B08L8L71SM",...],

tried that... the errors still keep popping up

**Comment by DakkJaniels** [comment]
Covered by #503
