### ISSUE TITLE
Amazon website change (Master branch issue)

### ISSUE THREAD

**Issue by DakkJaniels** [Hari-Nagarajan/fairgame#503]
Amazon is moving away from offer listing page (OLP) and moving to the all offers display (AOD) which includes a flyout/sidebar on the right side of the page for the offers. When requesting the OLP page, there is a very high chance that it will redirect to the product data page with the AOD shown.

As a result, the master branch is broken until we merge in development branch code. If you keep seeing failed to load prices, start using the development branch. No need to post new issues about how Master doesn't work, we already know.

**Comment by NeighborWithSugar** [comment]
where can i find the development branch

**Comment by DakkJaniels** [comment]
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-branches#switching-between-branches

**Comment by DaveBarman** [comment]
Will it be merged to master soon? I am having issues executing the development branch.

**Comment by unapproachable** [comment]
This issue is resolved by release 0.6.0
