### ISSUE TITLE
Making the bot choose Fast Shipping at the checkout

### ISSUE THREAD

**Issue by halesiacarolina** [Hari-Nagarajan/fairgame#506]
Hello, i have an idea, it would be great if the bot would have a feature like selecting fast delivery instead of standard delivery. I'm trying to buy on my local amazon but Amazon Eu Sarl is the seller so they ship abroad. If I choose Standard Delivery at the checkout, they ship with the worst shipping carrier; APG. However, if i choose Prioritized Delivery, they ship with UPS or DHL. So if the bot could choose the second option, this would make a huge difference. Thank you.
![fast shipping](https://user-images.githubusercontent.com/77868583/107884819-0b9a1180-6f08-11eb-9010-f69a85c5383d.jpg)

**Comment by DakkJaniels** [comment]
Please submit a PR for it, if you would like it implemented.

**Comment by unapproachable** [comment]
Unlikely the bot will be updated to support selecting options with cost implications.  The difference between 119 and 181 is significant and could put people outside of their min/max range.  If someone submits a PR with an implementation, please include corresponding user configuration for the various options that may be presented.
