### ISSUE TITLE
Issue while running "pipenv install". PS: I have a Raspberry Pi 3 B

### ISSUE THREAD

**Issue by Spaccapicchio** [Hari-Nagarajan/fairgame#509]
(fairgame) pi@raspberrypi:~/fairgame $ pipenv install
Pipfile.lock not found, creating...
✘ Locking Failed! 
pyobjc; sys_platform == 'darwin' doesn't match your environment, its dependencies won't be resolved.
Could not find a version of pywin32; sys_platform == 'win32' that matches your environment, it will be skipped.
ERROR:pip.subprocessor:Command errored out with exit status 1:
 command: /home/pi/.local/share/virtualenvs/fairgame-3Td2oUte/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-resolver-ha0xgkzh/lxml/setup.py'"'"'; file='"'"'/tmp/pip-resolver-ha0xgkzh/lxml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-resolver-ha0xgkzh/lxml/pip-egg-info
     cwd: /tmp/pip-resolver-ha0xgkzh/lxml/
Complete output (3 lines):
Building lxml version 4.6.2.
Building without Cython.
Error: Please make sure the libxml2 and libxslt development packages are installed.

**Comment by DakkJaniels** [comment]
Did you follow the instructions for raspberry pi?

**Comment by Spaccapicchio** [comment]
Yes, I also installed Pillow as the specific guide for pi says.

**Comment by bmn001** [comment]
I was also getting an error about "locking failed" and things not matching my environment.

While not running on a Pi, I am running Ubuntu and eventually got it working.  Try my solution [here](https://github.com/Hari-Nagarajan/fairgame/issues/465#issuecomment-781620560) and see if it works?

**Comment by Spaccapicchio** [comment]
Thank you, it seems a nice solution. I'll try it.

**Comment by Guilhem30** [comment]
try to install libxml2-dev and libxslt-dev with apt.
You will probably get another error that require you to install rust later, I used this https://rustup.rs/

**Comment by unapproachable** [comment]
Updates to the documentation and encryption library dependencies should hopefully resolve this issue.
