### ISSUE TITLE
Selenium cert issues. No site will load in launched chrome instance.

### ISSUE THREAD

**Issue by griffinmartin** [Hari-Nagarajan/fairgame#516]
**Describe the bug**
The chrome selenium instance opened by fairgame will display `Your connection is not private` on any site entered into that browser.

**To Reproduce**
1. Start bot
2. Attempt to load smile.amazon.com or any other website
3. Receive `Your connection is not private` error

**Expected behavior**
Websites load without cert issues.

**Screenshots**
If applicable, add screenshots to help explain your problem. These are found in the bot directory.
![Screen Shot 2021-02-24 at 11 18 57 AM](https://user-images.githubusercontent.com/1090329/109046645-39aeec80-7692-11eb-85cf-a7c1c22046e5.png)

**Desktop (please complete the following information):**
 - OS: OSX 
 - Version 11.2.1

**Additional context**

**Comment by DakkJaniels** [comment]
I have not heard of anyone else having this issue, and I haven't seen it myself. Are you sure you don't have something running that is causing this issue, unrelated to the bot? Are you running the master branch?

**Comment by unapproachable** [comment]
You'll need to do more to determine why it's not secure.  Inspect the cert. in the browser and see if it says what's causing it to fail the security check.  It should list out the hurdles it clears and the ones it doesn't leading to the downgraded security rating.

**Comment by griffinmartin** [comment]
I'm running master branch. This started happening after the last OSX update.

I believe it may have corrupted my chrome install. 
![Screen Shot 2021-02-24 at 5 29 26 PM](https://user-images.githubusercontent.com/1090329/109084895-e0f94700-76c5-11eb-9553-546d6c7a6158.png)

Going to reinstall chrome with brew and report back.

@unapproachable every website inside the selenium chrome instance has a cert issue.

**Comment by DakkJaniels** [comment]
I assume if you open chrome normally you don't see these cert errors?

**Comment by titanbrave** [comment]
I'm having the same issue. I've done everything but it's just not working.

**Comment by titanbrave** [comment]
Figured it out, you have to install the "python certificates" after you've installed python. If you read through the installer it tells you to do it after. I skipped over it! Worked after I'd done that.

**Comment by griffinmartin** [comment]
> python certificates

I have python3 installed via brew. I have followed numerous threads with no luck.
ex) [https://stackoverflow.com/questions/46626103/ssl-error-after-brew-install-python3](https://stackoverflow.com/questions/46626103/ssl-error-after-brew-install-python3)

Will report back if I find anything that works. Thanks for the heads up on where to look!
