### ISSUE TITLE
'Amazon.sg Checkout' is not a known page title

### ISSUE THREAD

**Issue by wheresisaac** [Hari-Nagarajan/fairgame#518]
**Describe the bug**
While testing with a random amazon item, the script is unable to recognize amazon.sg checkout page, and goes into a loop.

**To Reproduce**
using amazon.sg as website in config file

**Expected behavior**

**Screenshots**
![cmd](https://user-images.githubusercontent.com/54135077/109098271-f8830f00-775b-11eb-9035-4b3a86cfcad9.png)
![checkout](https://user-images.githubusercontent.com/54135077/109098272-f9b43c00-775b-11eb-990f-1e1aab272400.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Additional context**

**Comment by unapproachable** [comment]
Adding "GRATIS LIEFERUNG FÜR PRIME-MITGLIEDER" to "FREE_SHIPPING"  node of Fairgame for next release.  Documenting here for others having similar issues.
