### ISSUE TITLE
Can't parse html when send notification usign telegram

### ISSUE THREAD

**Issue by giuseppe99barchetta** [Hari-Nagarajan/fairgame#519]
I'm trying to send notification using telegram but when send notification the href tag does not being parsed, can you explain me how to resolve?

Thanks a lot!

**Comment by DakkJaniels** [comment]
No idea unless you actually show what you did.

**Comment by giuseppe99barchetta** [comment]
Sorry.. 

I'm trying to send notification usign this function in amazon.py:

```
 self.send_notification(
                            message="<a href=\"https://amazon.it/dp/{asin}\">test</a>",
                            page_name="Stock Alert",
                            take_screenshot=False,
                        )

```
but when notification are delivered to telegram what i see is only html, like this: 

`<a href="https://amazon.it/dp/A00000000">test</a>`

It's possibile to do somethings to parse html?

Thanks

**Comment by DakkJaniels** [comment]
huh? You said the string should be `"<a href=\"https://amazon.it/dp/{asin}\">test</a>"` and it wrote `"<a href=\"https://amazon.it/dp/{asin}\">test</a>"` (with the ASIN filled in of course). 

Not really sure what the issue is, but it doesn't sound like it's a bot issue, sounds like a telegram issue?

**Comment by giuseppe99barchetta** [comment]
> huh? You said the string should be `"<a href=\"https://amazon.it/dp/{asin}\">test</a>"` and it wrote `"<a href=\"https://amazon.it/dp/{asin}\">test</a>"` (with the ASIN filled in of course).
> 
> Not really sure what the issue is, but it doesn't sound like it's a bot issue, sounds like a telegram issue?

I don't think it's a telegram problem beacuse i already do it with other python and java bots. When sending message with this method there's no parser for html.

```
    def message_sender(self):
        while True:
            message, ss_name = self.queue.get()

            if ss_name:
                self.apb.notify(body=message, attach=ss_name)
            else:
                self.apb.notify(body=message)
            self.queue.task_done()
```

Using telegram library for sending message can be used parse_mode = 'html' for parse html when sending message

**Comment by DakkJaniels** [comment]
I guess if you would like there to be a html parser, you are welcome to add it or modify the code accordingly? What has been included meets the purposes we intended (notifications in plain text with what the bot is doing).

**Comment by giuseppe99barchetta** [comment]
> I guess if you would like there to be a html parser, you are welcome to add it or modify the code accordingly? What has been included meets the purposes we intended (notifications in plain text with what the bot is doing).

I can't understand how works notification, I never used like this
