### ISSUE TITLE
--checkshiping result's in no node found

### ISSUE THREAD

**Issue by Serva3** [Hari-Nagarajan/fairgame#520]
![image](https://user-images.githubusercontent.com/73985205/109182272-cf15b380-775a-11eb-8036-edcca147046a.png)

When you have checkshipping enabled and the seller is from a third party, you get no node found.

Edit: 
Yeah so --checkshipping wasn't able to count the shipping (count = 0) from a third party seller that ships the item and is the only seller for the item.

**Comment by DakkJaniels** [comment]
Can you show the webpage? All that means is that it couldn't parse the shipping price, so it assumes it is 0.

**Comment by megalomenyak** [comment]
cause 3 party seller dont send your location.

**Comment by unapproachable** [comment]
@Serva3  ASIN list and configuration parameters (basically amazon_config.json) would really, really help in recreating this issue and debugging it.

**Comment by DakkJaniels** [comment]
Closing this based on edit, unless you indicate that the price was within bounds and it didn't work or provide some information on what the shipping actually was.
