### ISSUE TITLE
ERROR with Check Out 

### ISSUE THREAD

**Issue by tiago199988** [Hari-Nagarajan/fairgame#523]
Im having issues placing orders in Spainsh version of amazon.

Screenshots of error and web page where it fails.

![InkedInkederror 1_LI](https://user-images.githubusercontent.com/34251062/109241443-500f9200-77d1-11eb-891c-1e73c26d0e69.jpg)

![erro 2](https://user-images.githubusercontent.com/34251062/109241317-13dc3180-77d1-11eb-9847-56edbe43c6a4.PNG)

**Comment by tiago199988** [comment]
I took a look at the code and fixed it my self 

just have to add `"A preparar o seu pedido" ` in `"CHECKOUT_TITLES":`
Also add `"Obrigado, o seu pedido foi efetuado"` in "ORDER_COMPLETE_TITLES":

**Comment by DakkJaniels** [comment]
pushing this into dev. Closing
