### ISSUE TITLE
Stuck on Opening Amazon Flyout

### ISSUE THREAD

**Issue by athenawisdoms** [Hari-Nagarajan/fairgame#524]
**Describe the bug**
The bot is stuck when trying to open the flyout on the right side of the page on Amazon. The entire page is dimmed but the flyout is visible has a tall strip of undimmed region on the right side of page. The bot is stuck here and no longer continues to the page of the next ASIN that it should check.

**To Reproduce**
1. Run `app.py amazon`
2. Enter credentials file password
3. Wait for several hours

**Expected behavior**
The flyout on the right side of page should contain data about the existing offer. After evaluating the offers, the bot should navigate to the webpage of the next ASIN, or add the offer to cart and check out.

**Screenshots**
![image](https://user-images.githubusercontent.com/6615285/109254055-38c7a900-77bf-11eb-93a1-138ab49f61e6.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Google Chrome Version 88.0.4324.182 (Official Build) (64-bit)
 - Version: 0.6.0

**Additional context**
Occurs several times a day. There are only 6 ASINS in `amazon_config.json`. `amazon_website` is `smile.amazon.com`.

**Comment by athenawisdoms** [comment]
Looks like it is getting stuck at the same page, even when the flyout appears...

The chrome browser is also not responsive to user input. Clicking and scrolling does nothing. Bot works as expected after restarting the bot.

![image](https://user-images.githubusercontent.com/6615285/109332834-a8c04880-782c-11eb-8652-51ef6cc0fd00.png)

**Comment by DakkJaniels** [comment]
99.9% sure this is an Ubuntu issue. Computer stats?

**Comment by athenawisdoms** [comment]
@DakkJaniels 
- AMD Ryzen 3950X
- 128 GB DDR
- RTX 2070S & RTX 270S
- 2 TB M2 NVMe
- Ubuntu 20.04.1 LTS
- GNOME 3.36.8

Any suggestions?

**Comment by gtrak** [comment]
Fairgame works fine for me on ubuntu.  I had some issues with installing
the dependencies, and I'm not sure what my workaround was, but it doesn't
seem related to this issue.

**Comment by gtrak** [comment]
Oh, I had some crashes and disabled gpu accel, you might try that.

```
@@ -1502,17 +1503,14 @@ class Amazon:
                 prefs["profile.managed_default_content_settings.images"] =
0
             options.add_experimental_option("prefs", prefs)
             options.add_argument(f"user-data-dir={path_to_profile}")
+            options.add_argument("--disable-gpu")
             if not self.slow_mode:
                 options.set_capability("pageLoadStrategy", "none")
```

**Comment by DakkJaniels** [comment]
Yeah that might be it, only say it's a Ubuntu issue (maybe any *nix system though) because I only ever see people bring up the unresponsive problems when they are using those systems. Please let me know if the above fix resolves the problem @athenawisdoms,

**Comment by athenawisdoms** [comment]
Will post an update after letting it run for a day or so with the `--disable-gpu` flag. Thank you!

**Comment by athenawisdoms** [comment]
@gtrak @DakkJaniels Problem appears to be fixed. Bot running flawlessly for 3 days. Thanks!
