### ISSUE TITLE
Saw Dogs for "ASIN:

### ISSUE THREAD

**Issue by gamerrrrrboy** [Hari-Nagarajan/fairgame#544]
I'm running 2 bots one for 3070 and one for 3080. The 3080 bot keeps getting the Issue Saw dogs for "ASIN" Skipping... but for the 3070s I never run into this issue. Any suggestions or fixes? I'm really sure how to provide steps on this because im assuming its unique to me.

**Comment by unapproachable** [comment]
Without information about what ASINs or what your configuration is, no, I don't have any suggestions.  You should see the dogs in the browser and if so, I'd guess you have a bad ASIN.

**Comment by hunkyburrito3** [comment]
I had this issue earlier due to my own stupidity, and I suggest you make sure that all punctuation is correct. (ie: quotes, commas, brackets)

**Comment by gamerrrrrboy** [comment]
I checked all the ASINS and they are all valid and the config file is correct.

**Comment by DakkJaniels** [comment]
That's great, but you going to post any screenshots or something, or just ask for help without showing us anything?

**Comment by gamerrrrrboy** [comment]
Would you like a screenshot of the config file or?

**Comment by DakkJaniels** [comment]
That, your terminal screen, what the browser looks like when this occurs, what flags you are running to run the program... _anything_

**Comment by MrNormalNinja** [comment]
Same thing happening to me. Everything worked fine. I changed nothing in config. Today it just stopped working. Here is an imgur link

https://imgur.com/a/UARRoCT

**Comment by shroyhammer** [comment]
This just happened to me also.
Anyone know how to fix it?
Here's the config, terminal, and chrome browser display pics
![saw dogs terminal](https://user-images.githubusercontent.com/79087957/111511401-ed445300-870b-11eb-8760-731183963271.png)
![saw dogs](https://user-images.githubusercontent.com/79087957/111511404-eddce980-870b-11eb-8539-d885d1f0861e.png)
![saw dogs config](https://user-images.githubusercontent.com/79087957/111511407-ee758000-870b-11eb-8369-bd0f1598c9fb.png)

This sucks, please help!

**Comment by shroyhammer** [comment]
I did it!  If you look at the asin numbers above from my last post, you'll see there's a bunch of weird shit added after the "/".
Not sure how that happened, as I didn't add it, but I thought it looked weird when I screen shot/posted here and sure enough, it's a bunch of SHIT.
YEET AND DELETE that, now it should look something like this:
![FIX](https://user-images.githubusercontent.com/79087957/111512632-2d580580-870d-11eb-8066-838741b09423.png)
Now you're good to go, golden showers, off to the races, takin' the piss, ya bunch of gromley mingers!

**Comment by DakkJaniels** [comment]
@shroyhammer that is weird, considering you are the one that is supposed to edit that file, we don't have any of that stuff in the template, and the readme only has the alphanumeric ASIN, and not all that other stuff. Very weird indeed. 🤷🏽‍♂️
