### ISSUE TITLE
"Timed out waiting for the flyout to open..."

### ISSUE THREAD

**Issue by asoupspoon** [Hari-Nagarajan/fairgame#545]
I have been using this program to try and get myself a graphics card for about 2 weeks now. I just now tested it on some preworkout. Put in the correct value

{
  "asin_groups": 1,
  "asin_list_1": ["B074PXN6ZY"],
  "reserve_min_1": 10,
  "reserve_max_1": 20,
  "amazon_website": "smile.amazon.com"
}

This program should auto get this because the product is available. I get the following error: 
2021-03-03 19:27:42|0.6.0|ERROR|Timed out waiting for the flyout to open and populate.  Is the connection slow?  Do you see the flyout populate?
2021-03-03 19:27:52|0.6.0|ERROR|Timed out waiting for the flyout to open and populate.  Is the connection slow?  Do you see the flyout populate?

This repeats itself until I exit the program. 
What does this mean and how can I fix this?

**Comment by DakkJaniels** [comment]
Are you minimizing the browser window?

**Comment by asoupspoon** [comment]
> 
> 
> Are you minimizing the browser window?

No. Google chrome is open and so is the program.

**Comment by DakkJaniels** [comment]
What does the browser look like? Screenshots? Any flags you are running with the program?

**Comment by asoupspoon** [comment]
> 
> 
> What does the browser look like? Screenshots? Any flags you are running with the program?

cmd /k pipenv run python app.py amazon --delay=1 --no-image --single-shot --no-screenshots --checkshipping

This is what the _Amazon   looks like. 

The browser is just sitting there like normal with nothing done to it. Ill grab a SC really fast

**Comment by DakkJaniels** [comment]
Didn't see #532?

**Comment by asoupspoon** [comment]
> 
> 
> Didn't see #542 ?



> 
> 
> Didn't see #542 ?

I did not! Thats what I get for watching some random Youtube video. That worked! I am the proud new owner of some preworkout!
