### ISSUE TITLE
ImportError: cannot import name 'Config' from 'config' (unknown location) Ubuntu 

### ISSUE THREAD

**Issue by dropitlikecross** [Hari-Nagarajan/fairgame#562]
**Describe the bug**
First time install.

Trying to run it after following the ubuntu installation guide and I'm getting:
```

Traceback (most recent call last):
  File "app.py", line 51, in <module>
    from cli import cli
  File "//home/fairgame/cli/cli.py", line 44, in <module>
    from common.globalconfig import GlobalConfig, AMAZON_CREDENTIAL_FILE
  File "/home/fairgame/common/globalconfig.py", line 21, in <module>
    from config import Config as Cfg
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser : Chrome that is linked in fairgame documentaion
 - Version 

Extra context:

I'm running it from the pipenv shell

```
python3 --version
Python 3.8.5
```

When I was running it for the first time, some requirements were missing like click, coloredlogs etc.. and I installed them with pip3

**Comment by DakkJaniels** [comment]
you can also install `config` with pip3 then.
