### ISSUE TITLE
Locking Failed! Error

### ISSUE THREAD

**Issue by Jaywik7** [Hari-Nagarajan/fairgame#570]
**ERROR im getting in CMD while installing**
C:\Users\My PC\Documents\GitHub\fairgame>pipenv install
Warning: Your Pipfile requires python_version 3.8, but you are using unknown (C:\Users\My PC\.\f\S\python.exe).
  $ pipenv --rm and rebuilding the virtual environment may resolve the issue.
  $ pipenv check will surely fail.
Pipfile.lock not found, creating...
**Locking** [dev-packages] dependencies...
           Building requirements...
Resolving dependencies...
Locking Failed!
Unable to create process using 'c:\users\my pc\appdata\local\programs\python\python38\python.exe "c:/users/my pc/appdata/local/programs/python/python38/lib/site-packages/pipenv/resolver.py" --dev --write c:/users/mypc~1/appdata/local/temp/resolver55pohgvv.json'

**Desktop:**
 - Win 10
 - Python 3.8.8

**Comment by DakkJaniels** [comment]
![image](https://user-images.githubusercontent.com/6080734/111535290-56918980-873f-11eb-9330-67d570df91cb.png)

**Comment by Jaywik7** [comment]
Ok will try installing to the "C:\Pythn38"

Thanks
