### ISSUE TITLE
timed out waiting for offer

### ISSUE THREAD

**Issue by vayn69420** [Hari-Nagarajan/fairgame#571]
After it checked for stock it times out waiting for offers
![image](https://user-images.githubusercontent.com/80860407/111598259-5345de80-87cf-11eb-8175-ee7351bd5d36.png)

**Comment by DakkJaniels** [comment]
Because you didn't set up AmazonSmile correctly and pick a charity.

**Comment by warfjm** [comment]
I'm having the same problem and I have a charity picked.

![offers to render](https://user-images.githubusercontent.com/81491617/112768941-5dd45500-8fd3-11eb-9912-a0fc0c6cdc11.png)
