### ISSUE TITLE
No Module named click?

### ISSUE THREAD

**Issue by Jarradmorden** [Hari-Nagarajan/fairgame#572]
![problem](https://user-images.githubusercontent.com/43785305/111628056-b0e62500-87e7-11eb-8711-5f958f1f677d.PNG)
I am getting No Module named click? when running the _amazon bat, i have installed it via pip to make sure.. 

any ideas?

**Comment by DakkJaniels** [comment]
Yes, since the virtual environment was just created when you did that, you didn't run `INSTALL (RUN FIRST).bat`

**Comment by Jarradmorden** [comment]
Yes I already ran this

**Comment by DakkJaniels** [comment]
Then it didn't run correctly, so lets see the output from that.

**Comment by DakkJaniels** [comment]
Also show the whole terminal window, not a part of it.

**Comment by oinkmode** [comment]
> Also show the whole terminal window, not a part of it.

I also want to see it. He may have ran it as ADMIN.

**Comment by jsunstrom** [comment]
I had the same problem. I was able to get it fixed with the following command:

pipenv install click

**Comment by DakkJaniels** [comment]
While it is true that `pipenv install click` will install `click` it seems unlikely that all the other modules were installed except for `click` so that problem likely needs to be fixed. Unless they want to do `pipenv install XXXX` for sixty-something modules.

**Comment by Jarradmorden** [comment]
Hey guys i do apologise for not replying, let me try some things and get back to you!

**Comment by Jarradmorden** [comment]
Okay so just as a test "pipenv install click" was installed and it was the only module missing and it now works.

**Comment by jsunstrom** [comment]
> While it is true that `pipenv install click` will install `click` it seems unlikely that all the other modules were installed except for `click` so that problem likely needs to be fixed. Unless they want to do `pipenv install XXXX` for sixty-something modules.

I agree. I just thought it worth mentioning that `click` was indeed the only module that did not install correctly for me.

**Comment by Jarradmorden** [comment]
> > While it is true that `pipenv install click` will install `click` it seems unlikely that all the other modules were installed except for `click` so that problem likely needs to be fixed. Unless they want to do `pipenv install XXXX` for sixty-something modules.
> 
> I agree. I just thought it worth mentioning that `click` was indeed the only module that did not install correctly for me.

same to me
