### ISSUE TITLE
Bot won't add to cart with warning message: |NOT YET IMPLEMENTED: PDP represents only item worth considering.  No other sellers available. TODO: Parse pricing and Add To Cart from PDP if item qualifies.

### ISSUE THREAD

**Issue by lyantrux** [Hari-Nagarajan/fairgame#573]
**Describe the bug**
Bot won't add to cart with warning message: |NOT YET IMPLEMENTED: PDP represents only item worth considering. No other sellers available. TODO: Parse pricing and Add To Cart from PDP if item qualifies.

**To Reproduce**
1. Use below config 
    {
  "asin_groups": 1,
  "asin_list_1": ["B085FY422G"],
  "reserve_min_1": 1,
  "reserve_max_1": 10,
  "amazon_website": "smile.amazon.com"
}
2. run the bot by pyton app.py amazon
3. Amazon logged in fine, loading PDP fine, but then it keeps saying WARNING|NOT YET IMPLEMENTED: PDP represents only item worth considering.  No other sellers available. TODO: Parse pricing and Add To Cart from PDP if item qualifies. 

**Expected behavior**
Add to cart and checkout 

**Screenshots**

<img width="799" alt="Screen Shot 2021-03-18 at 9 26 40 AM" src="https://user-images.githubusercontent.com/45796189/111633637-175d4a00-87cc-11eb-8fd5-7b1f982638fa.png">

 - OS:  MacOS Big Sir 11.2
 - Browser Chrome
 - Version 89.0.4389.82

**Comment by DakkJaniels** [comment]
try `--slow-mode`. Also you don't need to open an issue for something that there is an error message that says NOT IMPLEMENTED YET, since we clearly know about this.

**Comment by shawnli87** [comment]
@DakkJaniels What does this error mean? I just tried to migrate to an Ubuntu server, and I'm getting this error on every item I test. My Mac at home does not have this issue.

**Comment by DakkJaniels** [comment]
It means what it says.

Development branch implemented parsing PDP now.

**Comment by DakkJaniels** [comment]
Also the AOD did not pop up, which may occur if there is only one seller.

**Comment by shawnli87** [comment]
Cool thanks so much for being condescending for absolutely no reason

**Comment by DakkJaniels** [comment]
Cool, I don't know what what to tell you. The master branch has not yet implemented parsing the PDP, exactly what the error message says.

**Comment by shawnli87** [comment]
Obviously I don't know what PDP means, which is why I asked what the error meant. And that doesn't explain why it would occur on one device and not another. But it's all good, us peons who don't know Amazon terminology and acronyms are clearly beneath you and we shouldn't bother trying to learn and help troubleshoot.

**Comment by DakkJaniels** [comment]
That's not obvious because you didn't ask that. Discord has more info about all of this in #tech-support pins, please look there if you are interested.

I have no idea why two systems could act differently, but it is likely because the server provided different responses. You didn't say anything about where the systems are located, of they are on the same IP, etc., so what am I supposed to do?

**Comment by DakkJaniels** [comment]
But regardless there is nothing to troubleshoot because the fix is already in the development branch.

**Comment by lyantrux** [comment]
Thank you @DakkJaniels .

Tried develop branch and the issue was resolved.

**Comment by DakkJaniels** [comment]
@lyantrux my bad, it looks like the fix hasn't been pulled into development yet (but it shows that Amazon's website is a little unpredictable). The fix is actually in the features/housekeeping branch.

**Comment by lyantrux** [comment]
@DakkJaniels Yes my bad too I meant to say housekeeping. I was looking branch by branch to find the one with the most recent commit and found it:) Tested and purchased a small thing for $5 and it works like a charm, took 7 seconds to checkout. Thank you for doing this for us.
