### ISSUE TITLE
Certificate Issue

### ISSUE THREAD

**Issue by Alavaramantisi** [Hari-Nagarajan/fairgame#576]
When I run the amazon.bat, I receive this error;

[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

what should I do?

I am using anaconda prompt.

Can you please help me?

**Comment by DakkJaniels** [comment]
did you run `INSTALL (RUN FIRST).bat` ? If so, run it again and show me the screenshot.

**Comment by Alavaramantisi** [comment]
yes I ran it. 
![Ekran Alıntısı](https://user-images.githubusercontent.com/64653569/111689704-6d1e0a80-883d-11eb-9569-1b8b3d6b511d.PNG)

**Comment by DakkJaniels** [comment]
I asked for a screenshot of you running `INSTALL (RUN FIRST).bat`

**Comment by DakkJaniels** [comment]
Also, I have no idea if this actually works for Anaconda (the answer is probably not). You should use Python 3.8.5-3.8.8 as stated in the readme

**Comment by Alavaramantisi** [comment]
Ah misunderstood I guess. Here it is,
![Ekran Alıntısı](https://user-images.githubusercontent.com/64653569/111691356-45c83d00-883f-11eb-9ea6-ab695fbcf0e7.PNG)
when I press any key the window closes.
