### ISSUE TITLE
Bot Crashes with  f"You are running FairGame v{version.release}, but the most recent version is v{version.get_latest_version()}. "

### ISSUE THREAD

**Issue by SirDystic** [Hari-Nagarajan/fairgame#586]
Trying to launch 0.60 Dev and i get a crash:

pipenv run python app.py amazon --delay=2 --checkshipping

    FairGame Copyright (C) 2021 Hari Nagarajan
        This program comes with ABSOLUTELY NO WARRANTY; for details
        start the program with the `show --w' option.

        This is free software, and you are welcome to redistribute it
        under certain conditions; for details start the program with
        the `show --c' option.

Traceback (most recent call last):
  File "app.py", line 51, in <module>
    from cli import cli
  File "C:\temp\Bot1-UK-XXX\cli\cli.py", line 345, in <module>
    f"You are running FairGame v{version.release}, but the most recent version is v{version.get_latest_version()}. "
AttributeError: 'Version' object has no attribute 'get_latest_version'

**Comment by DakkJaniels** [comment]
Resolved under #585
