### ISSUE TITLE
Stuck at "Evaluating Offers"

### ISSUE THREAD

**Issue by H4TERAID** [Hari-Nagarajan/fairgame#596]
**Describe the bug**
Stuck at "Evaluating offers" will not click buy or proceed to check out. See pic at bottom.

**To Reproduce**

Just start the bot.

**Expected behavior**
The item that is in stock to be purchased.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Latest
 - Browser: Chrome
 - Version : 0.62

**Additional context**
She's dead jim.

![33](https://user-images.githubusercontent.com/53838616/111890180-7504b880-89bd-11eb-9a96-cfec67643f08.png)

**Comment by DakkJaniels** [comment]
`--no-images` is broken, see #542, also hard to tell what's going on without screenshots of browser and your config.

**Comment by H4TERAID** [comment]
--no-images works great on my end, and it was because I had the low buy threshold set too high and the highest buy, set too high, im sorry totally noobed out. <3 you can close this.
