### ISSUE TITLE
Stuck at shipping iptions?

### ISSUE THREAD

**Issue by forcefed** [Hari-Nagarajan/fairgame#614]
My bot is stuck at the shipping options screen with the --test flag, is this normal behaviour? Shouldn't it at least get to the place order page? I added --checkshipping to include the shipping costs, also added --shipping-bypass to get past the "choose and address" page right before this one but here it gets stuck.

![bot](https://user-images.githubusercontent.com/81333267/112697536-23957700-8e5e-11eb-84df-304929a6cab0.jpg)

**Comment by DakkJaniels** [comment]
Follow directions in readme
