### ISSUE TITLE
__INSTALL (RUN FIRST) is not installing correctly

### ISSUE THREAD

**Issue by warfjm** [Hari-Nagarajan/fairgame#620]
Reinstalling Python 8.8.8 doesn't seem to work.  See the screenshot below.  Thanks for your help!

![_INSTALL Screen Shot](https://user-images.githubusercontent.com/81491617/112735609-96f4c280-8f0a-11eb-9a50-2ac84b8a74bf.png)

**Comment by DakkJaniels** [comment]
Follow directions. Install python to PATH.
