### ISSUE TITLE
AFTER A FEW MINUTES AMAZON ASKS FOR CAPTCHA

### ISSUE THREAD

**Issue by Neffa87** [Hari-Nagarajan/fairgame#634]
Hello to all. As the title suggests, after a few minutes the bot crashes and amazon asks me to enter the captcha.
I specify that I use the bot only on a single article.

everything is set to default except the command string in the _Amazon.bat file (cmd / k pipenv run python app.py amazon --single-shot --no-screenshots --delay = 5 --no-image)

How can I solve? thanks

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 89.0.4389.90

**Comment by Neffa87** [comment]
![Cattjjjjura](https://user-images.githubusercontent.com/81470840/113305581-79a56700-9303-11eb-9385-6e0950d3fd67.PNG)

**Comment by infinia** [comment]
Remove the no image command as it will prevent the bot from solving captchas I believe.

**Comment by geektechniquestudios** [comment]
> --delay = 5

This shouldn't have spaces before and after the `=`.  I'm not positive that's your issue though.

**Comment by Neffa87** [comment]
even without the no image command it does not work. even in headless mode.

the space in the command --delay = 5 is not present

**Comment by PikeTemplar** [comment]
Hi, I experience exactly the same issue, I launched 3 bot on 3 different VM and it asks for captcha after few minutes on each bot per VM.
I launched each bot with this command :
`pipenv run python app.py amazon --checkshipping --log-stock-check --single-shot`
![image](https://user-images.githubusercontent.com/42735493/114086757-4e96b680-98b3-11eb-8043-f907c4a5d8ea.png)
Why this captcha popup and bot can't solve it ?
