### ISSUE TITLE
Issue with bit not selecting use this address

### ISSUE THREAD

**Issue by Blueskys379** [Hari-Nagarajan/fairgame#637]
**Describe the bug**
The issue I'm having is the bot is getting stuck on checkout looking for proceed to checkout button but on screenshot it wants the use this address button pressed.

The strange part is this is only happening from GPUs sold directly through manufacturer on Amazon at msrp. Bot performed perfectly with 3rd party sellers as it bought a GPU no problem well above msrp as it didn't get stuck with selecting address. Also I ran bot with another Amazon product and performed no problem and didn't ask to use this address. It appears to be only happening with actual GPU drops. Also there is no other address for it to choose either. Is there a way for the bot to click this button if pops up?

**Comment by DakkJaniels** [comment]
![image](https://user-images.githubusercontent.com/6080734/113358732-5636e800-9314-11eb-8005-638acd86e8d1.png)

**Comment by Blueskys379** [comment]
Thank you! I’ll try that

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
