### ISSUE TITLE
WARNING|NOT YET IMPLEMENTED: PDP represents only item worth considering.  No other sellers available. TODO: Parse pricing and Add To Cart from PDP if item qualifies.

### ISSUE THREAD

**Issue by Doorknobs69** [Hari-Nagarajan/fairgame#638]
The Item shows as in stock and I get the following error, when it should just check out and purchase the item

2021-04-02 13:20:32|0.6.2|WARNING|NOT YET IMPLEMENTED: PDP represents only item worth considering.  No other sellers available. TODO: Parse pricing and Add To Cart from PDP if item qualifies.

![image](https://user-images.githubusercontent.com/81824921/113438789-44f2e780-93b7-11eb-9c49-6154285dd6cd.png)

**Expected behavior**
It should move to check out and process the order

**Screenshots**
If applicable, add screenshots to help explain your problem. These are found in the bot directory.
![image](https://user-images.githubusercontent.com/81824921/113438828-5936e480-93b7-11eb-809c-0d9ba136ca41.png)

**Comment by danielfriskey23** [comment]
I'm having the same issue while testing on a $1 USB flash drive

**Comment by DakkJaniels** [comment]
@danielfriskey23 then stop running old code
