### ISSUE TITLE
Every time I run "__INSTALL (RUN FIRST)" I get an error on Windows 10

### ISSUE THREAD

**Issue by warturtle99** [Hari-Nagarajan/fairgame#640]
Every time I run "__INSTALL (RUN FIRST)" on Windows 10 I the following error:

'pip' is not recognized as an internal or external command,
operable program or batch file.

What can I do to fix this?

![image](https://user-images.githubusercontent.com/81841986/113466890-78a43080-93fc-11eb-8fcb-44b6103fee8a.png)

**Comment by DakkJaniels** [comment]
Click the checkbox to install to path when you install Python.

**Comment by warturtle99** [comment]
> Click the checkbox to install to path when you install Python.

What checkbox am I selecting?

![image](https://user-images.githubusercontent.com/81841986/113467626-742e4680-9401-11eb-9642-4faa8a8a1cd0.png)

**Comment by DakkJaniels** [comment]
The one before that, per the readme.

**Comment by warturtle99** [comment]
> The one before that, per the readme.

Thank you so much! I really appreciate the help! Where is the  amazon_config.template_json file?

**Comment by DakkJaniels** [comment]
in the config folder.
