### ISSUE TITLE
Log in if  logged out

### ISSUE THREAD

**Issue by lr1100** [Hari-Nagarajan/fairgame#646]
Beacuse of #627 we are clearing  the  cache to  get  the  bot  to  work.

This logs you out.

Is there anyway the bot can check login, and log  back in if it isn't?

Doesn't  seem to  log  back in during a checkout   attempt, and you really don't  want  it  to do it  there because you waste precious seconds.

**Comment by DakkJaniels** [comment]
Yes, it should already log you back in. Obviously it cannot bypass 2FA or OTPs though. If it's not logging back in when it sees that page during a checkout attempt, need to see logs to deal with that.

**Comment by lr1100** [comment]
does it attempt during the checkout phase? trying  to  understand.
if  so, I think it should relog you  back in before  a checkout happens,   that  way the checkout is as fast as  possible.

**Comment by DakkJaniels** [comment]
If it sees the login page during checkout it will attempt to log back in. How is the bot supposed to know when to log you back in before a checkout? If you are clearing cookies, why don't you log in yourself in a separate tab?

**Comment by lr1100** [comment]
I wasn't trying to argue. I just feel like a check during it's normal loop could log you back in if you are logged out.
That way when an item does come available, you don't have to waste time logging in.
More automation will make the bot better in  my opinion.

**Comment by DakkJaniels** [comment]
Then please implement it in the code and submit a PR.
