### ISSUE TITLE
Buy only Prime items

### ISSUE THREAD

**Issue by RygarNelson** [Hari-Nagarajan/fairgame#664]
As the title says, I want to make a modification on the code so that the bot will only place orders and buy items from vendors that have the "Prime" enabled (mostly directly from Amazon).
Is it possible to do that? If so, how can I do it?

Thank you in advance for your patience.

**Comment by DakkJaniels** [comment]
Maybe that's possible, but you would have to modify the check_stock code.

**Comment by RygarNelson** [comment]
I have checked the "check_stock" function, but it is very long and cumbersome to modify. Any help? 
Thank you again in advance.

**Comment by DakkJaniels** [comment]
No, sorry. You'll have to look at the code that's there and figure out how to pull the appropriate parts of the webpage. It's not just changing two lines of code.

**Comment by RygarNelson** [comment]
Okay. Thank you
