### ISSUE TITLE
_amazon.bat

### ISSUE THREAD

**Issue by z00g** [Hari-Nagarajan/fairgame#671]
**Describe the bug**
Amazon bat run completely fine until i get the error key
![keyerror](https://user-images.githubusercontent.com/82400294/114427088-b1f75000-9bf5-11eb-846f-53a6bbcde28b.JPG)

Error: 'username'
**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. These are found in the bot directory.

**Desktop (please complete the following information):**

**Additional context**

**Comment by computerworxdev** [comment]
Hello I added item to amazon config and
I saw in browser getting stuck at the checkout procedure
See attached image

It would get stuck at that window when adding item and it would just do 
it in the loop
It could not process it…


However I got it to work only when I added to config –headless

Then order was processed

Is it a bug? Or better to run it in headless mode?

Also does it support other stores like bestbuy or only amazon ?

And 1 more question

If I have in config 10 amazon items… will they get check every few 
seconds simultaneously or 1 at the time for availability?


Thanks

**Comment by DakkJaniels** [comment]
@computerworxdev the answers to most of your questions can be found in the readme, you should read it.
No image was attached, but the product could have gone out of stock before you could check out.

**Comment by computerworxdev** [comment]
Ok when i run the script it was showing in stock but could not pass the 
check out point

When I run the script Headless it was successful.
See pic here
https://imgur.com/a/G5LkcwZ

**Comment by DakkJaniels** [comment]
Post your config file and what flags you ran the program with when it didn't work.

**Comment by DakkJaniels** [comment]
Also post screenshot of your terminal
