### ISSUE TITLE
Can't resolve Amazon domains after hours of botting

### ISSUE THREAD

**Issue by PikeTemplar** [Hari-Nagarajan/fairgame#672]
**Describe the bug**
After hours of good working, the bot can't resolve the Amazon domains (www.amazon.es / www.amazon.fr / www.amazon.de).
Even using Firefox instead of Chrome, can't resolve the domains.
Meanwhile I **can** resolve any other domain (like google.com, microsoft.com, etc.) on Chrome (the same browser as the bot).
To solve it I need to restart the host (VM).
 
**To Reproduce**
1. Launch the bot using the command "pipenv run python app.py amazon --checkshipping --log-stock-check --single-shot"
2. Wait something like 10-20 hours of bot usage.
3. Check the Terminal and the WEB browser to see the issue.

**Expected behavior**
Normally it should resolve the domains efficiency no matter how much time the bot is running (24/24 & 7/7).
I shouldn't to be forced to reboot the host (VM).

**Screenshots**
`Terminal + web browser during a normal running session of the bot`
![image](https://user-images.githubusercontent.com/42735493/114462041-ce3dc180-9be2-11eb-9a73-767ad6b7eb1f.png)
`Terminal + web browser after the bug happens`
![image](https://user-images.githubusercontent.com/42735493/114462142-f3cacb00-9be2-11eb-8f48-8cb09ef90d03.png)

**Desktop**
 - OS: Ubuntu 20.04.2 LTS (64-bit) up-to-date
 - Google Chrome
 - Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by PikeTemplar** [comment]
I can provide any configuration file if needed.
Only the json file is modified by the way.

**Comment by DakkJaniels** [comment]
If you can't even resolve a domain outside of the bot, this is not a bot issue.

**Comment by PikeTemplar** [comment]
I think you didn't read my post, 

> Meanwhile I **CAN** resolve any other domain (like google.com, microsoft.com, etc.) on Chrome (the same browser as the bot).

Only domains affected by the bot are not responding.

**Comment by DakkJaniels** [comment]
I did read it - I said, if you can't even resolve "a domain", as in, the domain in issue. Something is blocking your access, what does that have to do with this program?

**Comment by PikeTemplar** [comment]
I can resolve the domain, but after a couple of hours it stop responding.

**Comment by PikeTemplar** [comment]
The first screen shows that the bot can resolve the domains at the beginning (when I launch it) but after like 10-20 hours the domains are not responding/unresolved.
And it affects only amazon domains.

**Comment by DakkJaniels** [comment]
Again, if you cannot resolve a domain OUTSIDE OF THAT BOT that you are continuously sending requests to after 20 hours, how is that an issue with this software? SOMETHING ELSE is blocking you, you need to figure that out and it is not an issue that can be resolved here.

**Comment by PikeTemplar** [comment]
I don't see where it comes from as the only domains affected are the domains used by the bot.
That why I thought it came from the bot it's just impossible ?
This bug never happened ?

**Comment by DakkJaniels** [comment]
I don't know what to tell you. Issues resolving DNS are outside the scope of this project.
