### ISSUE TITLE
Amazon.ca is not a valid Checkout page?

### ISSUE THREAD

**Issue by smwasi98** [Hari-Nagarajan/fairgame#673]
**Describe the bug**
The program finds the product and makes it all the way to the place the order page, but proceeds to fail to checkout, not recognizing what the Order page is,

**To Reproduce**
1. Edit the config file for a product that is desirable in my case a sandisk USB
2. Change amazon domain to amazon.ca, because smile.amazon.ca does not exisit.
3. Run the bot
4. Error is produced within 10-15 seconds

**Expected behavior**
The bot is supposed to place the order for the account, in this way only detection of products is occurring and not the actual purchase of them.

**Screenshots**
![Screenshot at Apr 12 17-34-29](https://user-images.githubusercontent.com/59067662/114466008-e519ef00-9bb5-11eb-8dcb-6cb9f11c210b.png)
![screenshot-Amazon ca Checkout_04-12-2021_13_52_12](https://user-images.githubusercontent.com/59067662/114466376-696c7200-9bb6-11eb-8d00-b480a9160437.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.2.3 (latest)
 - Browser: Chrome for Intel Macs
 - Version: 89

**Additional context**
Would just like clarification if this is a known issue, in which case I'd look into contributing to the bot so it adequately works for Canadians, everything works just the last button Place Order is not clicked.

**Comment by DakkJaniels** [comment]
Add it to checkout_titles in fairgame.conf. We'll include in repo next time there is an update.

**Comment by smwasi98** [comment]
Great thanks, I'll test it out right now and close the issue;

**Comment by smwasi98** [comment]
Issue resolved quite easily simply follow DakkJaniels advice and add the checkout title to the conf file, should be fixed in the next release of the Fairgame Bot.
