### ISSUE TITLE
Fails to Add To Cart

### ISSUE THREAD

**Issue by korom42** [Hari-Nagarajan/fairgame#677]
**Describe the bug**
Bot cannot add the product to cart, stuck on "Please confirm your action screen"

**Screenshots**
![bug atc fail](https://user-images.githubusercontent.com/42497826/114651774-7c796200-9cdc-11eb-93c7-72ca6bcfcacd.jpg)
[Imgur](https://imgur.com/pYNSR8l)
[failed-atc_source_04-14-2021_04_25_48.zip](https://github.com/Hari-Nagarajan/fairgame/files/6308052/failed-atc_source_04-14-2021_04_25_48.zip)
[fairgame.log](https://github.com/Hari-Nagarajan/fairgame/files/6308053/fairgame.log)
clicking continue manually seems to make the bot able to reach checkout.

**Desktop (please complete the following information):**
 - OS: W10
 - Browser chrome
 - Version 89

**Additional context**
the part below this line should be revised, maybe use a different method to click the button?
` def attempt_atc(self, offering_id, max_atc_retries=DEFAULT_MAX_ATC_TRIES):`

**Comment by DakkJaniels** [comment]
Why should a different method be used?

Did you change your zoom? Can't tell because I can't see the whole browser.

**Comment by korom42** [comment]
> Why should a different method be used?
> 
> Did you change your zoom? Can't tell because I can't see the whole browser.

Yess, resetting windows size fixed this issue .Thanks a lot !Please check the other bug #678
