### ISSUE TITLE
Stuck at payment Option - Unable to complete checkout

### ISSUE THREAD

**Issue by korom42** [Hari-Nagarajan/fairgame#678]
**Describe the bug**
Bot is unable to continue due to grayed out button on payment screen. This happens if you made an order and your card was fozen or declined.

![bug2](https://user-images.githubusercontent.com/42497826/114666938-c2432400-9cf6-11eb-9538-11455af0b91a.jpg)
![bug3](https://user-images.githubusercontent.com/42497826/114666950-c66f4180-9cf6-11eb-9a4f-7ccc2b9f3e3e.jpg)
[fairgame.log](https://github.com/Hari-Nagarajan/fairgame/files/6308754/fairgame.log)
[pyo-error_source_04-14-2021_07_38_39.zip](https://github.com/Hari-Nagarajan/fairgame/files/6308757/pyo-error_source_04-14-2021_07_38_39.zip)

**Desktop (please complete the following information):**
 - OS:W10
 - Browser Chrome
 - Version 89

**Additional context**
I suggest adding a code when the bot arrives to this payment page and finds the buttons greyed out and do the following :
1- select the first available payment option
2- It will ask it to enter the cc number, this should be saved into in the bot config file amazon_config.json or with the AMZ account credentials

**Comment by DakkJaniels** [comment]
Nope, not saving credit card info with the bot. Set things up correctly as described in the readme.
