### ISSUE TITLE
Bot Reads Price Incorrectly

### ISSUE THREAD

**Issue by lordsilver** [Hari-Nagarajan/fairgame#683]
Unlike other European stores that use the dot as thousands separator, Amazon.fr uses the space. This means that the bot will read something like "1 770" as "1", leading to unwanted purchases.

**Comment by timbru31** [comment]
Please share an example product/link so we can debug

**Comment by lordsilver** [comment]
> Please share an example product/link so we can debug

Any product with a price of at least €1000 works. Anyway, here you go: https://www.amazon.fr/dp/B0918YP8T8/

**Comment by DakkJaniels** [comment]
I think we have to do a replace &nbsp with nothing. Price parser module doesn't handle it, I guess

**Comment by timbru31** [comment]
> I think we have to do a replace &nbsp with nothing. Price parser module doesn't handle it, I guess

Nope sadly it does not. I've made a small PR to catch these cases.
