### ISSUE TITLE
Error after chrome update

### ISSUE THREAD

**Issue by naked-head** [Hari-Nagarajan/fairgame#688]
Today I had updated my Debian system with a simple apt update and restarted fairgame.

After that I get this error:
Message: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 90.0.4430.72 with binary path /usr/bin/google-chrome

2021-04-16 08:43:42|0.6.2|ERROR|If you have a JSON warning above, try cleaning your profile (e.g. --clean-profile)
2021-04-16 08:43:42|0.6.2|ERROR|If that's not it, you probably have a previous Chrome window open. You should close it.

How can I solve it?
Thanks

**Comment by naked-head** [comment]
I solved setting system wide the python version, in Debian 10 I had to install python 3.8.8 manually, and reinstall fairgame after this setting.

**Comment by mgerb** [comment]
I just ran into this issue as well. If others are still having issues, running `pipenv update` and then `pipenv install` inside the fairgame directory worked  for  me.
