### ISSUE TITLE
Bot doesn't use "Buy It Now"

### ISSUE THREAD

**Issue by UnifiedOblivion** [Hari-Nagarajan/fairgame#689]
The bot doesn't use "Buy It Now" when purchasing. It will add to cart and go from there. I have 1-click purchasing enabled on chrome and tested it as well as the bot purchasing something that was in stock. It just adds to cart and attempts to go from there.

OS: Windows 10

**Comment by IvanShift** [comment]
https://github.com/Hari-Nagarajan/fairgame/issues/613#issuecomment-808137706
