### ISSUE TITLE
Bot goes from the cart to address select screen despite 1-Click enabled and default payment/address set.

### ISSUE THREAD

**Issue by janderson2494** [Hari-Nagarajan/fairgame#690]
When I manually go through in a separate tab to make my purchase everything works fine and it uses my default payment/shipping options, but when the bot gets something in the cart it goes from the cart to the address select screen every time. I have my default payment and address set, as well as 1-Click settings enabled, so I'm not really sure how to resolve this.

**Comment by DakkJaniels** [comment]
Get's something in your cart, like a test item? or a GPU?

**Comment by janderson2494** [comment]
A GPU specifically. Test items will work just fine.

**Comment by DakkJaniels** [comment]
![image](https://user-images.githubusercontent.com/6080734/115056772-3aede000-9eb1-11eb-90c7-eae634e266da.png)
![image](https://user-images.githubusercontent.com/6080734/115056813-46410b80-9eb1-11eb-86de-81aa59d7838f.png)
(Don't use development branch for this, it is in master now)
