### ISSUE TITLE
reached maximum ATC attempts, returning to stock check

### ISSUE THREAD

**Issue by dg6546** [Hari-Nagarajan/fairgame#697]
"reached maximum ATC attempts, returning to stock check" What does it mean?
![atc](https://user-images.githubusercontent.com/16924142/115097972-e9505e80-9f5f-11eb-9c3e-ed017cf1c14f.png)
![screenshot-failed-atc_04-17-2021_09_30_45](https://user-images.githubusercontent.com/16924142/115098013-23b9fb80-9f60-11eb-8847-bec44e3b0f08.png)

**Comment by DakkJaniels** [comment]
read the readme
