### ISSUE TITLE
Amazon added new buttons that fairgame can't detect

### ISSUE THREAD

**Issue by theseimpression** [Hari-Nagarajan/fairgame#701]
Can't add an RTX 3080 in cart because amazon added a new "continue" button that fairgame can't detect. Also, they added a new shipping option that fairgame ignores and goes back to the product page. The error that I got was "can't find purchase button" then "moving on to next product"

PLEASE FIX

**Comment by DakkJaniels** [comment]
HOW WOULD YOU LIKE THIS FIXED IF YOU DON'T PROVIDE ANYTHING LIKE SCREENSHOTS OR PAGE SOURCE?

**Comment by theseimpression** [comment]
> HOW WOULD YOU LIKE THIS FIXED IF YOU DON'T PROVIDE ANYTHING LIKE SCREENSHOTS OR PAGE SOURCE?

![Screenshot (188)](https://user-images.githubusercontent.com/82747071/115161443-7e338480-a052-11eb-9570-a80127a9d996.png)
![Screenshot (190)](https://user-images.githubusercontent.com/82747071/115161507-f39f5500-a052-11eb-928e-f892338007ce.png)
