### ISSUE TITLE
Amazon adds new buttons pt. 2

### ISSUE THREAD

**Issue by theseimpression** [Hari-Nagarajan/fairgame#704]
Can't add an RTX 3080 in cart because amazon added a new "continue" button that fairgame can't detect. Also, they added a new shipping option that fairgame ignores and goes back to the product page. The error that I got was "can't find purchase button" then "moving on to next product"

PLEASE FIX

![image](https://user-images.githubusercontent.com/82747071/115162717-dae66d80-a059-11eb-8f05-193cb8c17b6f.png)
![image](https://user-images.githubusercontent.com/82747071/115162720-df128b00-a059-11eb-8aa1-f993eab3a426.png)

**Comment by DakkJaniels** [comment]
Are you attempting to use Amazon smile? Did you pick a charity?

Regardless that's not a new continue button, it's out of stock when it tries to add.

**Comment by theseimpression** [comment]
So adding a charity should fix the continue and shipping problem?

**Comment by DakkJaniels** [comment]
Following the directions in the README would help, since there is no way you were going to place that order successfully. It doesn't magically make stock, or guarantee that you can purchase very in demand items though.
