### ISSUE TITLE
Solver doesnt start solving

### ISSUE THREAD

**Issue by Vanquiish** [Hari-Nagarajan/fairgame#719]
![Not working](https://user-images.githubusercontent.com/82958901/115793907-479c9780-a3cd-11eb-96f3-9b2c71090dcc.png)

I have installed the AmazonCaptcha Lib and even though it is installed the solver didnt started.

So how do i get my solver running? 
Do i have to create another source file and paste the suggested code? or do i have to integrate the suggested code into amazon.py ?

**Comment by DakkJaniels** [comment]
Is there a captcha? What you showed makes no indication there is one. Show the browser window.

**Comment by Vanquiish** [comment]
![not working2](https://user-images.githubusercontent.com/82958901/115794697-bc240600-a3ce-11eb-9963-9f062ca75f88.png)

**Comment by DakkJaniels** [comment]
Captcha showed up immediately? Did home page come up first?

**Comment by Vanquiish** [comment]
no, captcha showed up immediately...

**Comment by DakkJaniels** [comment]
There is no check for captcha right when it loads the home page, I have never seen that before. How many bots are you running? What delay?

**Comment by Vanquiish** [comment]
Right now 1 Bot with a delay of 3 sec. in the past ive tried running 3 bots simultaneously after those attempts it started with the captchas.

**Comment by Vanquiish** [comment]
I found a response from u like 2 Weeks ago, where u said to put the domain into CAPTCHA_PAGE_TITLES so the bot recognizes that there is a captcha to be solved. 
![fixed the bot](https://user-images.githubusercontent.com/82958901/115797466-4753ca80-a3d4-11eb-9e0a-ba23c352ac9a.png)

**Comment by DakkJaniels** [comment]
Oh that's good. I thought I had pulled that in for some other pages, but I guess I didn't.
