### ISSUE TITLE
Bot buys wrong thing

### ISSUE THREAD

**Issue by powellplayz7** [Hari-Nagarajan/fairgame#723]
I have the bot on a 3060, and this recent drop, it says that an order has been placed. However, when i check the order, (i have the correct asin) it shows that I have ordered this: https://www.amazon.com/gp/product/B07FCLPPXQ/ref=ppx_yo_dt_b_asin_title_o01?ie=UTF8&th=1
any help?

**Comment by DakkJaniels** [comment]
Don't add things to your cart while the bot is running.
