### ISSUE TITLE
Adding item to card > button clicked > you have no items in card

### ISSUE THREAD

**Issue by majoryikes** [Hari-Nagarajan/fairgame#724]
**Describe the bug**
An item comes in to stock in my price range, gets added to card, proceeds to checkout then says something like "no items found in cart" and goes back to checking

Item in stock and in reserve range
Adding to cart
Attempting to add to card with offer id
clicking button
button clicked
looking for proceed to checkout button
you have no items in cart. going back to check stock

**To Reproduce**

**Expected behavior**
It to pay for and successfully check out.

Sorry Im a noob guys....am I doing something wrong or just too many people/not enough cards?

**Comment by majoryikes** [comment]
Lol no answer, just closed?

**Comment by DakkJaniels** [comment]
![image](https://user-images.githubusercontent.com/6080734/115944249-a1ab6480-a482-11eb-971f-e8ef530ab0c0.png)

**Comment by majoryikes** [comment]
Gotcha. Thanks.
