### ISSUE TITLE
Not a bug Just a simple info

### ISSUE THREAD

**Issue by wes1993** [Hari-Nagarajan/fairgame#730]
Hello,
Thanks a lot for your simply and beautiful bot!!!
I have one question, there is a way to check with one bot instance different amazon website?
Thanks a lot
Stefano

**Comment by DakkJaniels** [comment]
no

**Comment by wes1993** [comment]
thanks for your reply :-D
We could consider this for a functionality in some new releases :-D

**Comment by DakkJaniels** [comment]
if someone implements it, sure.

**Comment by wes1993** [comment]
Perfect :-D
