### ISSUE TITLE
pip3 install pipenv macOS 

### ISSUE THREAD

**Issue by kantonuebrig** [Hari-Nagarajan/fairgame#744]
****I tried to install it on macOS but then a error message came****
**ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/Library/Python/3.8'
Consider using the `--user` option or check the permissions.

WARNING: You are using pip version 19.2.3, however version 21.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.**

**To Reproduce**
1. terminal
2. pip3 install pipenv
3. ERROR

macOS Big Sur Version 11.2.3
MacBook Air M1

If anyone could explain me why this happen, and what I can do please help!
Thanks

**Comment by DakkJaniels** [comment]
This is not really a bot issue.

https://www.google.com/search?q=ERROR%3A+Could+not+install+packages+due+to+an+EnvironmentError%3A+%5BErrno+13%5D+Permission+denied%3A+%27%2FLibrary%2FPython%2F3.8%27%EF%BB%BF+Consider+using+the+--user+option+or+check+the+permissions.%EF%BB%BF+%EF%BB%BF&oq=ERROR%3A+Could+not+install+packages+due+to+an+EnvironmentError%3A+%5BErrno+13%5D+Permission+denied%3A+%27%2FLibrary%2FPython%2F3.8%27%EF%BB%BF+Consider+using+the+--user+option+or+check+the+permissions

**Comment by kantonuebrig** [comment]
Yeah thanks it is all new for me I guess I have to look into it !
