### ISSUE TITLE
Attempting Add To Cart with offer ID

### ISSUE THREAD

**Issue by aviatetheway** [Hari-Nagarajan/fairgame#749]
Attempting Add To Cart with offer ID...
Timed out reloading page, trying to continue anyway

Keeps stuck in this loop

Latest Version 0.6.6

![Untitled](https://user-images.githubusercontent.com/83025439/116743825-1882b900-a9bf-11eb-87df-17a720413964.png)

**Comment by DakkJaniels** [comment]
did you pick a charity?

**Comment by aviatetheway** [comment]
> did you pick a charity?

I have not

**Comment by DakkJaniels** [comment]
why not?

**Comment by aviatetheway** [comment]
I just did now and still having the same problem

2021-04-30 14:41:15|0.6.6|INFO|Checking stock for items.
2021-04-30 14:41:17|0.6.6|INFO|No offers found.  Moving on.
2021-04-30 14:41:22|0.6.6|INFO|No offers found.  Moving on.
2021-04-30 14:41:37|0.6.6|ERROR|Timed out waiting for the flyout to open and populate.  Is the connection slow?  Do you see the flyout populate?
2021-04-30 14:41:47|0.6.6|WARNING|Timed out waiting for offers to render.  Skipping...
2021-04-30 14:41:47|0.6.6|WARNING|URL: https://smile.amazon.com/dp/B07XJ8C8F5
2021-04-30 14:41:52|0.6.6|INFO|Found 2 offers for B07XJ8C8F5.  Evaluating offers...
2021-04-30 14:41:52|0.6.6|INFO|Item B07XJ8C8F5 in stock and in reserve range: 29.99 + 0.00 shipping <= 1900.0
2021-04-30 14:41:52|0.6.6|INFO|Adding to cart
2021-04-30 14:41:52|0.6.6|INFO|Attempting Add To Cart with offer ID...
2021-04-30 14:41:58|0.6.6|INFO|Timed out reloading page, trying to continue anyway
2021-04-30 14:42:03|0.6.6|INFO|Timed out reloading page, trying to continue anyway
2021-04-30 14:42:08|0.6.6|INFO|Timed out reloading page, trying to continue anyway
2021-04-30 14:42:13|0.6.6|INFO|Timed out reloading page, trying to continue anyway
2021-04-30 14:42:18|0.6.6|INFO|Timed out reloading page, trying to continue anyway
2021-04-30 14:42:23|0.6.6|INFO|Timed out reloading page, trying to continue anyway
2021-04-30 14:42:29|0.6.6|INFO|Timed out reloading page, trying to continue anyway
2021-04-30 14:42:34|0.6.6|INFO|Timed out reloading page, trying to continue anyway
2021-04-30 14:42:39|0.6.6|INFO|Timed out reloading page, trying to continue anyway

**Comment by DakkJaniels** [comment]
Did you set up default address and payment method, and is one-click enabled?

**Comment by aviatetheway** [comment]
Yes all of them are set up. Could the soft ban be the issue here?

**Comment by DakkJaniels** [comment]
Maybe. Maybe you have to clear your cookies and log in again.

**Comment by aviatetheway** [comment]
Once I clear the cookies the flyout populates but does not add the item to the cart or complete the checkout process

**Comment by DakkJaniels** [comment]
what happens if you click this link?

https://smile.amazon.com/checkout/turbo-initiate?ref_=dp_start-bbf_1_glance_buyNow_2-1&pipelineType=turbo&weblab=RCX_CHECKOUT_TURBO_DESKTOP_NONPRIME_87784&temporaryAddToCart=1&offerListing.1=rSSU6XwKPZuV3agTXPBsoDrzSxNhPeeP6l8eBHwqVGhLDWXZvKGUgEhxoZZlVKyYSr0EjVp4a4ePQy27s8onXl4CXG8js1tnIOAYYFTibaF8wiwlXrpC%2FhB9ATGUizHDqHCo3JXWVO4ghRLr2ZodWg%3D%3D&quantity.1=1

**Comment by aviatetheway** [comment]
If I copy and paste the link into the browser. I get 

Access to smile.amazon.com was denied.
You don't have authorization to view this page.
HTTP ERROR 403

**Comment by DakkJaniels** [comment]
can you actually buy anything in the browser, manually?

**Comment by DakkJaniels** [comment]
using buy it now

**Comment by aviatetheway** [comment]
Yes on the same browser window it allows me, 

But it is not a one click process. I click Buy now and it brings me to another page to place the order.

**Comment by DakkJaniels** [comment]
what page did it bring you to?

**Comment by DakkJaniels** [comment]
if buy it now doesn't work for you, then you have to use `--alt-checkout`

**Comment by aviatetheway** [comment]
> what page did it bring you to?

Takes me to this page:

![Untitled](https://user-images.githubusercontent.com/83025439/116749183-2daf1600-a9c6-11eb-8f7f-1729ff9ab7c9.jpg)

**Comment by DakkJaniels** [comment]
are you sure you have 1-click set up? Did you verify it?

**Comment by aviatetheway** [comment]
On the regular amazon.com it is enabled. I cant access the .smile 
![Untitled](https://user-images.githubusercontent.com/83025439/116749733-fc831580-a9c6-11eb-804f-9e41655fe14c.png)

**Comment by DakkJaniels** [comment]
You have to enable it in the bot's browser. Is that the bot's browser? If you can't access it, and you haven't done it, it's probably not enabled.

**Comment by aviatetheway** [comment]
> You have to enable it in the bot's browser. Is that the bot's browser? If you can't access it, and you haven't done it, it's probably not enabled.

Since I can't access it on the bot browser what would I do? When I click on account it takes me to a Sorry we cant find that page.

**Comment by DakkJaniels** [comment]
I don't know.

**Comment by Sauromayne** [comment]
> > You have to enable it in the bot's browser. Is that the bot's browser? If you can't access it, and you haven't done it, it's probably not enabled.
> 
> Since I can't access it on the bot browser what would I do? When I click on account it takes me to a Sorry we cant find that page.
> 

If amazon won't let you access your account page means you are softbanned. So wait and activate it when you have access to the account page again?

**Comment by aviatetheway** [comment]
I was able to enable 1 click buying after the softban was removed.  But the bot gets stuck here and no purchase is made, 

![Untitled](https://user-images.githubusercontent.com/83025439/116770924-e13af900-aa0c-11eb-9638-aa73a0757621.png)

**Comment by DakkJaniels** [comment]
Can you screenshot the whole browser? was there a button there?

**Comment by aviatetheway** [comment]
Disregard just checked my orders page and it did make the purchase. Is it normal for the browser to close once the purchase is complete? Shouldn't there be a log in the cmd that the purchase went thru?

**Comment by DakkJaniels** [comment]
There is: 
![image](https://user-images.githubusercontent.com/6080734/116770986-d6389680-aa15-11eb-8cfb-aad5cc80b04a.png)

I don't know why it didn't pop up, but it literally says to check your orders because sometimes there are issues.

**Comment by DakkJaniels** [comment]
Also, yes, it's normal for the browser to close when it's no longer searching for anything and it shuts down the program.
