### ISSUE TITLE
FairGame Incorrect Version Reporting

### ISSUE THREAD

**Issue by SpiderTECH611** [Hari-Nagarajan/fairgame#753]
**Describe the bug**
FairGame is reporting that it is version 0.6.6 when it should be version 0.6.7

**To Reproduce**
1. Download, Install, and Setup FairGame v0.6.7 as per usual setup
2. Run _Amazon.bat within FairGame 0.6.7 Folder
3. FairGame reports "You are running FairGame v0.6.6, but the most recent version is v0.6.7. Consider upgrading"
4. FairGame continues to report Version 0.6.6 and Runs as usual

**Expected behavior**
Correct Reporting of version number v0.6.7

**Screenshots**
https://ibb.co/K0XKsv8

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 90.0.4430.93 (Official Build) (64-bit)

**Additional context**

**Comment by DakkJaniels** [comment]
fixed the release versioning
