### ISSUE TITLE
Proxy/ProxyConnector code not working as intended.

### ISSUE THREAD

**Issue by JoeyJojoShabado** [Hari-Nagarajan/fairgame#755]
New to python but I believe I'm seeing two issues in stores/amazon_monitor.py and AmazonMonitor class.

1. The class is already being instantiated by the time `assign_proxy` is called.  This results in the `self.proxy_connector = ProxyConnector.from_url(self.proxy)` not executing as proxy will always be `None`,  As a result `aio_get` will never execute the else block with  `self.get(url, connector=self.proxy_connector)`.  I corrected this by moving `self.get(url, connector=self.proxy_connector)` to within assign_proxy. 
2.  With `self.proxy_connector` now defined `aio_get` does fire the else block.  This leads to the next issue. `TypeError: _request() got an unexpected keyword argument 'connector'`.  ClientSession cant be passed a `connector` paramon a call to `get`. It needs to be passed on creation.  
 
Buy adding `connector=ProxyConnector.from_url(proxy)` to the AmazonMonitor creation in the `item_list` loop I was able to see traffic passing over my socks5 proxies.  Similar would need to be done in `self.fail_recreate` using the passed along.  Learned this as my proxies were already getting 503s in html_saves and triggered the re-creation of "new" un-proxied AmazonMonitors.  I may submit a PR, but I'm sure there's more elegant ways to accomplish

**Comment by DakkJaniels** [comment]
assignment fixed, I think
