### ISSUE TITLE
Still issues with the "use this address" button

### ISSUE THREAD

**Issue by 1buckeyefan** [Hari-Nagarajan/fairgame#756]
This has been reported several times in the past. I've tried the suggestions but I still get the bot to get past the use this address button. I've removed all of my payments methods and addresses. I've made a purchase where it forced me to enter a payment method and shipping address where I made them my default and they are my only methods. Still I'm getting prompted with the use this address button.

**Comment by DakkJaniels** [comment]
![image](https://user-images.githubusercontent.com/6080734/116914098-52023100-ac18-11eb-9802-c2c94f762f0a.png)
