### ISSUE TITLE
ERROR|couldn't find button to place order / Amazon.de

### ISSUE THREAD

**Issue by oebaran** [Hari-Nagarajan/fairgame#757]
Amazon.de gives problems tree Buy.
Test purchases work without problems with standard products.
Amazon has changed the page for certain articles.
Here is the bug and screen shot.

It would be great if the tool confirms the individual steps again.
Does something have to be programmed in Fairgame.conf?

![IMG_0068](https://user-images.githubusercontent.com/83680751/117087062-b3c4b700-ad4e-11eb-9f25-f9cbf139534b.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10
 - Browser [chrome]
 - Version [Newest]

**Comment by DakkJaniels** [comment]
![image](https://user-images.githubusercontent.com/6080734/117087160-a989c500-ad1c-11eb-9f9d-bb6aff77d7e0.png)

**Comment by oebaran** [comment]
the product is not out. I was able to manually confirm the order myself by
clicking the individual steps. It's a PS5 warehouse.

Thank you.

DakkJaniels ***@***.***> schrieb am Mi. 5. Mai 2021 um 03:07:

**Comment by DakkJaniels** [comment]
There is a flag to click the use this address button if that's the case. So you placed the order succesfully?

**Comment by oebaran** [comment]
I was able to order successfully.
I ordered before hectic that was, as I said, a used one which I canceled
again.

are you sure that the page will come if the article is not available
confirm with address?

can this be a bot security?

DakkJaniels ***@***.***> schrieb am Mi. 5. Mai 2021 um 03:16:

**Comment by DakkJaniels** [comment]
I'm sorry, I don't really understand what you are saying, in regards to the sequence that occurred. Are you saying that page appeared, and you clicked through everything? I don't understand why you cancelled it then. Or did you just click through something else that popped up, and that thing didn't ask you for your address?

**Comment by oebaran** [comment]
I was able to order successfully.
I ordered before hectic that was, as I said, a used one which I canceled
again.

are you sure that the page will come if the article is not available
confirm with address?

can this be a bot security?


I just saw that the item was available again.

with 0.6.2 he made aod = 1 directly does this method no longer exist?

DakkJaniels ***@***.***> schrieb am Mi. 5. Mai 2021 um 03:27:

**Comment by oebaran** [comment]
I thank you for your effort.

yes I want to say that I clicked my way through. I canceled the item
because it was used and not new.

My guess is that it may have been set up on the PS5 in the warehouse so
that you have to click through again?

Hamdi Öztürk ***@***.***> schrieb am Mi. 5. Mai 2021 um 03:32:
