### ISSUE TITLE
Delete Cookies in Headless Mode?

### ISSUE THREAD

**Issue by AlfaJackal** [Hari-Nagarajan/fairgame#776]
How can I delete cookies in headless mode? Is there any way?

**Comment by DakkJaniels** [comment]
https://www.google.com/search?q=how+can+I+delete+cookies+in+headless+chrome

**Comment by AlfaJackal** [comment]
> https://www.google.com/search?q=how+can+I+delete+cookies+in+headless+chrome

Cheers! I know how to use google. Since I am not a developer, the solutions suggested for Selenium did not help me. 

So if you have a solution that is workable for laymen, feel free to show it.

**Comment by DakkJaniels** [comment]
I don't, that's the point.
