### ISSUE TITLE
How to change the page refresh rate?

### ISSUE THREAD

**Issue by funisprime** [Hari-Nagarajan/fairgame#813]
![image](https://user-images.githubusercontent.com/75384845/128461249-507ebf4e-1276-45bb-babf-57b7aa12c2e9.png)

Problem
Opened the amazon.py file
cranked up all the settings from default_max_.... to default_max...
Ran the program and it still fails to delay on the refresh
The only variable that seems to make a difference in the login delay is the DEFAULT_PAGE_WAIT_DELAY = 0.5
How do i change the refresh rate of the program to avoid being aggressive and drawing the attention of amazon
I was asked to verify if i was human recently but no real signs of an issue yet

Expectation
I will at least like the program to refresh pages every 5 minutes or so

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

Context:
I am a big fan of fairgame because that is what it is a fairgame and i have been trying to get my hands on the PS5 for a while and it just seems impossible and amazon as a corporation might not understand the value of a person like Hari who realized that the game might be rigged.

Feedback will be appreciated.

**Comment by DakkJaniels** [comment]
Why would you open the amazon.py file and start making changes to the code? You think this isn't covered in the README already?

**Comment by funisprime** [comment]
i looked at the read me. either way, the bot is too aggressive.

**Comment by funisprime** [comment]
its not covered in the readme all you give are the consequences of it being aggressive. I need a way to change the agrression.

**Comment by DakkJaniels** [comment]
Ctrl-F
`Delay`

**Comment by funisprime** [comment]
i saw it. it is using the shell script, dumb me, I just dont understand this program at all and how you linked py code to shell but i guess i am so dumb. 
I added --delay FLOAT 50
is this the right syntax?
Moreover its too late as i now have to link another account

**Comment by DakkJaniels** [comment]
No, look at the examples in the readme right after the list of options.

**Comment by funisprime** [comment]
@DakkJaniels gracias/thank you amigo. I found the example.

You are a lifesaver.

You guys are gonna need to teach me your secrets of understanding this stuff.

**Comment by funisprime** [comment]
Thanks i will close the issue.

**Comment by DakkJaniels** [comment]
> You guys are gonna need to teach me your secrets of understanding this stuff.
> 

The secret is  reading documentation carefully and thoroughly, and using search to try and find if keywords are in documents (and trying different keywords). And Google for general Python stuff.
