### ISSUE TITLE
Bots adds item to cart repeatedly.

### ISSUE THREAD

**Issue by Dayng0** [Hari-Nagarajan/fairgame#814]
![Capture](https://user-images.githubusercontent.com/88757725/128964692-dd108a6b-ec26-4db5-bacb-0ece8b5409da.PNG)

The bot thinks that id did not add to cart, but it is actually adding it to my cart multiple times. Never makes it to the checkout screen

**Comment by funisprime** [comment]
so it seems there are products that the bot is unable to perform a checkout. I think this is just based on how amazon listed said product.

I have had the problem and so i tried an ASIN number that works till the checkout point and that worked indicating to me that there are products for which the bot will fail to complete the checkout process.

How and Why that happens is likely beyond my dumb brain.

**Comment by vCLAYMOREv** [comment]
I'm new to this and don't know how to solve this issue I tried random products it worked but most of GPUs don't work

**Comment by DakkJaniels** [comment]
The page html has changed (sometimes), which is what is causing the issue. The code needs to be updates to account for the modified page html.

**Comment by DakkJaniels** [comment]
closing this and keeping #815 open for this issue.
