### ISSUE TITLE
Crashes when it can't add item to cart because its already sold.  

### ISSUE THREAD

**Issue by Jay311xx** [Hari-Nagarajan/fairgame#816]
![FairgameAddToCart crash](https://user-images.githubusercontent.com/39271594/129798026-501a98ae-e3d1-4cf8-86ec-6e8e30106abd.png)

**Comment by DakkJaniels** [comment]
duplicate of #815

**Comment by Jay311xx** [comment]
opps sorry.  Feel free to delete this.
