### ISSUE TITLE
(Suggestion) Don't use your credentials while monitoring

### ISSUE THREAD

**Issue by polow** [Hari-Nagarajan/fairgame#824]
Only monitoring a few products on Amazon.com and sometimes it's giving me this error :

"Timed out waiting for the flyout to open and populate.  Is the connection slow?  Do you see the flyout populate?
2021-09-09 19:02:27|0.6.9|WARNING|Timed out waiting for offers to render.  Skipping...
2021-09-09 19:02:27|0.6.9|WARNING|URL: https://smile.amazon.com/dp/XXXXXXXX" 

Once i logout and rerun the bot all is fine, so why not login just in case product was found instead of bein logged in all the time ?
i know this might delay the checkout process but at least you don't have to deal with proxies.

**Comment by DakkJaniels** [comment]
Alpha branch already does this. Likely will not implement this in the branch that uses selenium for monitoring. Yes it would delay the checkout process significantly, and possibly halt it completely if there is a request for a OTP or other verification.
