### ISSUE TITLE
I can't run fairgame

### ISSUE THREAD

**Issue by kajmerap** [Hari-Nagarajan/fairgame#825]
hi, I downloaded and used the program before, but I needed a gpu again, I downloaded it, I did all the steps I did before, but an error appears as in the picture.
![Untitled](https://user-images.githubusercontent.com/81520149/133158944-c73adc1b-0d9f-4642-ab9e-6a3ca659d56e.png)

**Comment by DakkJaniels** [comment]
Follow all the directions in the readme, including where to install things.
