### ISSUE TITLE
Error Chrome version 92

### ISSUE THREAD

**Issue by polow** [Hari-Nagarajan/fairgame#829]
I updated my Chromedriver and now the script won't work anymore, I hope someone can help.

Error :  

2021-09-24 17:26:03|0.6.9|ERROR|Message: session not created: This version of ChromeDriver only supports Chrome version 92
Current browser version is 94.0.4606.61 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

2021-09-24 17:26:03|0.6.9|ERROR|If you have a JSON warning above, try cleaning your profile (e.g. --clean-profile)
2021-09-24 17:26:03|0.6.9|ERROR|If that's not it, you probably have a previous Chrome window open. You should close it.

Tried to download Chromedriver version 92,94 but can't figure out where to place it.

Chrome version 94.0.4606.61

**Comment by DakkJaniels** [comment]
master branch updated

**Comment by EliBork** [comment]
I am still getting this error after pulling the master branch. I also updated pipfile.lock.

**Comment by DakkJaniels** [comment]
did you run `pipenv install` like the readme says when you make code updates?

**Comment by EliBork** [comment]
I did not, thank you for the quick reply. The issue has been resolved, thank you for reminding me.

**Comment by molloymartin16** [comment]
hi it says
|Message: session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 97.0.4692.99 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
and 
If you have a JSON warning above, try cleaning your profile (e.g. --clean-profile)

**Comment by DakkJaniels** [comment]
Use lastest master branch
