### ISSUE TITLE
No config found

### ISSUE THREAD

**Issue by BigBoi132** [Hari-Nagarajan/fairgame#841]
I have tried several different version and all of the say, "No config found". I have made a copy of the "amazon_config" file and renamed to "amazon_config.json" and yet it still gives me the same issue. Any ideas on how to fix this?

**Comment by DakkJaniels** [comment]
You didn't actually rename it to `amazon_config.json`. Look at the screenshot in the directions. Reveal the file extensions.

**Comment by BigBoi132** [comment]
You're right, I wasn't viewing with file extensions and for some reason
that made my rename not work(new to all of this). Renamed it to the same as
it was before but including file extensions and it worked.

Thank you.
