### ISSUE TITLE
Amazon seems to have changed their URL scheme

### ISSUE THREAD

**Issue by neondiscokittens** [Hari-Nagarajan/fairgame#845]
ASINs no longer seem to work on smile.amazon.com/dp/*ASIN*

If I am looking at a product with ASIN ‎B097CMQVF4, and I go to smile.amazon.com/dp/‎B097CMQVF4, it redirects me to https://www.amazon.com/dp/%E2%80%8E‎B097CMQVF4 which doesn't exist. I have to manually remove "%E2%80%8E" and then it works. Is this just an issue for me?

**Comment by DakkJaniels** [comment]
It sounds like it still works, but you've added some extra characters to the ASIN. See #faq in Discord:
![image](https://user-images.githubusercontent.com/6080734/146689720-1810b85f-f278-4b81-8d65-0d672de40a72.png)

**Comment by DakkJaniels** [comment]
For reference, your post looks like this when I post it to Notepad++ and change it to ANSI encoding:
![image](https://user-images.githubusercontent.com/6080734/146699210-cb80e73c-e423-4499-b54d-d3b80391c43a.png)
