### ISSUE TITLE
This version of chrome driver only supports chrome version 90?

### ISSUE THREAD

**Issue by Hov45** [Hari-Nagarajan/fairgame#851]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. These are found in the bot directory.

**Desktop (please complete the following information):**

**Additional context**

**Comment by xiurobert** [comment]
Man, you literally did not even edit the default template. This issue is completely useless. Are you on Windows or Mac/Linux? Man, if only you filled out the issue form.

You will need to update and install Chrome, and install the latest version of ChromeDriver.

**Comment by DakkJaniels** [comment]
use master branch
