### ISSUE TITLE
The "add to cart" button no longer works

### ISSUE THREAD

**Issue by Legendmode** [Hari-Nagarajan/fairgame#852]
Hello everyone. For a few days the bot has crashed with an error on the product and does not add it to the cart. Until a few weeks ago everything was working fine. I have done some tests and it crashes with the following error:
2022-02-09 08:27:40|0.6.9|ERROR|failed to find //input[@value='add' and @name='add']

Version:
 - google chrome Versione 98.0.4758.82
- amazon.co.uk - amazon.de - amazon.it - amazon.fr - amazon.es

![unknown](https://user-images.githubusercontent.com/98160714/153142143-b5a8aba4-11c4-44f6-a38f-328a2b7c83af.png)
![unknown (1)](https://user-images.githubusercontent.com/98160714/153142227-bb1997a8-4cb7-4252-aff2-6810051e1e1c.png)

Can anyone help me solve the problem? thank you

**Comment by Code-Red-666** [comment]
Same issue here

**Comment by charloti** [comment]
Yup, I'm facing the same problem. Thanks for helping

**Comment by Sylensky** [comment]
iam experiencing the same behaviour

**Comment by Sylensky** [comment]
small research on the discord lead to the following working conclusion brought up from Rudi:
replace this line: https://github.com/Hari-Nagarajan/fairgame/blob/master/stores/amazon.py#L942 
with: `xpath = "//*[@id='a-autoid-0']/span/input"`
