### ISSUE TITLE
ERROR: This version of ChromeDriver only supports Chrome version 91

### ISSUE THREAD

**Issue by Dandydoo** [Hari-Nagarajan/fairgame#854]
**Describe the bug***
While initialising Amazon.bat this Error comes:  

|ERROR|Message: session not created: This version of ChromeDriver only supports Chrome version 91
Current browser version is 98.0.4758.102 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
**To Reproduce**

**Expected behavior**
Expected it´s ok with newest Chrome

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser G Chrome
 - Version 98.0.4758.102 (Feb 14 2022)

Running Python 3.8.8 64 bit and Fairgame 0.6.9

**Additional context**
only works with installing the 91 Version. But then, Chrome is useless on my PC.

I hope you can help :)

**Comment by DakkJaniels** [comment]
use master branch

**Comment by Dandydoo** [comment]
but how? I´m Python beginner :)
