### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 97

### ISSUE THREAD

**Issue by charloti** [Hari-Nagarajan/fairgame#857]
**Describe the bug**
Message: session not created: This version of ChromeDriver only supports Chrome version 97
Current browser version is 99.0.4844.74 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

How does one update the pipfile?

**Comment by FrankyBBoy** [comment]
Same problem here:

> 2022-04-01 11:28:40|0.6.9|ERROR|Message: session not created: This version of ChromeDriver only supports Chrome version 98
> Current browser version is 100.0.4896.60 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

I'm updated on the last Chrome version and still have the problem. Any known workaround?

**Comment by DakkJaniels** [comment]
update pipfile by opening it and putting in the correct version for the chromedriver-py.

**Comment by FrankyBBoy** [comment]
> update pipfile by opening it in a text editor and putting in the correct version for the chromedriver-py.

Thank you @DakkJaniels, that works!

And for python noobs like me, you also have to re-install with the command `pipenv install` or by running "__INSTALL (RUN FIRST).bat" again after updating the pipfile

**Comment by jakubgt** [comment]
> update pipfile by opening it in a text editor and putting in the correct version for the chromedriver-py.

I changed the pipfile to my current chrome driver, but when I run _INSTALL (RUN FIRST).bat I get  this error

Pipfile.lock (d2db7a) out of date, updating to (16d2eb)...
Locking [dev-packages] dependencies...
           Building requirements...
Resolving dependencies...
Success!
Locking [packages] dependencies...
           Building requirements...
Resolving dependencies...
Locking Failed!
pyobjc; sys_platform == 'darwin' doesn't match your environment, its dependencies won't be resolved.
CRITICAL:pipenv.patched.notpip._internal.index.package_finder:Could not find a version that satisfies the requirement chromedriver-py==100.0.4896.88 (from -r C:\Users\jakub\AppData\Local\Temp\pipenv8tyu3m7erequirements\pipenv-0rs6v4ji-constraints.txt (line 10)) (from versions: 2.38, 2.45.2, 2.45.3, 2.46, 78.0.3904.11, 78.0.3904.70, 79.0.3945.16, 79.0.3945.36, 80.0.3987.16, 81.0.4044.20, 81.0.4044.69, 83.0.4103.14, 83.0.4103.39, 84.0.4147.30, 85.0.4183.38, 85.0.4183.83, 85.0.4183.87, 86.0.4240.22, 87.0.4280.20, 87.0.4280.88, 88.0.4324.27, 88.0.4324.96, 89.0.4389.23, 90.0.4430.24, 91.0.4472.19, 92.0.4515.43, 92.0.4515.107, 93.0.4577.15, 93.0.4577.63, 94.0.4606.41, 95.0.4638.10, 95.0.4638.17, 96.0.4664.18, 96.0.4664.35, 96.0.4664.45, 97.0.4692.20, 97.0.4692.36, 97.0.4692.37, 97.0.4692.71, 98.0.4758.48, 98.0.4758.80, 98.0.4758.102, 99.0.4844.17, 99.0.4844.35, 99.0.4844.51, 100.0.4896.20, 100.0.4896.60, 101.0.4951.15)
[ResolutionFailure]:   File "c:/python38/lib/site-packages/pipenv/resolver.py", line 741, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "c:/python38/lib/site-packages/pipenv/resolver.py", line 702, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "c:/python38/lib/site-packages/pipenv/resolver.py", line 684, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "c:\python38\lib\site-packages\pipenv\utils.py", line 1395, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   File "c:\python38\lib\site-packages\pipenv\utils.py", line 1108, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "c:\python38\lib\site-packages\pipenv\utils.py", line 833, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: No matching distribution found for chromedriver-py==100.0.4896.88 (from -r C:\Users\jakub\AppData\Local\Temp\pipenv8tyu3m7erequirements\pipenv-0rs6v4ji-constraints.txt (line 10))

I also get the same error when I try to launch the program after updating the pipfile:

 |Message: session not created: This version of ChromeDriver only supports Chrome version 98 
Current browser version is 100.0.4896.88 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by DakkJaniels** [comment]
100.0.4896.88 does not match a release of chromedriver-py: 
![image](https://user-images.githubusercontent.com/6080734/163175215-e7e041d1-0921-4c04-a11e-fbd4790b9f87.png)
